import {normalizeTheme,applyTheme} from './theme.js';
export {THEMES} from './theme.js';
export const TABLE_SIZES=[['compact','Compact'],['standard','Standard'],['spacious','Spacious']];
export const LANGUAGES=[['en','English'],['ar','العربية']];
export const TIME_ZONES=[['UTC','UTC'],['Asia/Riyadh','Saudi Arabia / KSA · UTC+3'],['Asia/Dubai','United Arab Emirates · UTC+4'],['Asia/Bahrain','Bahrain · UTC+3'],['Europe/London','United Kingdom'],['Europe/Paris','Central Europe'],['America/New_York','New York'],['Asia/Kolkata','India'],['Asia/Tokyo','Japan']];
export const DEFAULT_PREFERENCES={language:'en',timeZone:'UTC',theme:'light',tableSize:'standard'};
export function normalizePreferences(value={},strict=false){
  const language=value?.language??'en',timeZone=value?.timeZone??'UTC';
  const validLanguage=LANGUAGES.some(([v])=>v===language),validZone=TIME_ZONES.some(([v])=>v===timeZone);
  if(strict&&(!validLanguage||!validZone))throw new Error('Choose a supported language and time zone.');
  const tableSize=value?.tableSize??'standard',validSize=TABLE_SIZES.some(([key])=>key===tableSize);
  if(strict&&!validSize)throw new Error('Choose a supported table size.');
  return {tableSize:validSize?tableSize:'standard',language:validLanguage?language:'en',timeZone:validZone?timeZone:'UTC',theme:normalizeTheme(value?.theme??'light',strict)};
}
let preferences={...DEFAULT_PREFERENCES};
export function setPreferences(value){preferences=normalizePreferences(value);if(typeof document!=='undefined'){document.documentElement.lang=preferences.language;document.documentElement.dir=preferences.language==='ar'?'rtl':'ltr';applyTheme(preferences.theme);document.documentElement.setAttribute?.('data-table-size',preferences.tableSize);}return preferences;}
export const getPreferences=()=>({...preferences});
export function formatDate(value){if(!value)return '—';const date=new Date(value);if(!Number.isFinite(date.getTime()))return '—';return new Intl.DateTimeFormat(preferences.language==='ar'?'ar-SA-u-ca-gregory':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:preferences.timeZone}).format(date)+' · '+preferences.timeZone;}
export const formatNumber=value=>Number.isFinite(value)?new Intl.NumberFormat(preferences.language).format(value):'—';
const AR={
 'Workflow status':'حالة سير العمل',
 'Automation is ready. New matching scans will be assigned automatically.':'الأتمتة جاهزة. سيتم إسناد حالات الفحوصات الجديدة المطابقة تلقائيًا.',
 'Automation is not enabled. Create and enable a rule to start assignment, review notifications and escalation.':'الأتمتة غير مفعلة. أنشئ قاعدة وفعّلها لبدء الإسناد وإشعارات المراجعة والتصعيد.',
 'Enabled rules reference unavailable accounts. Edit the investigator, reviewer and escalation recipient before automation can run.':'القواعد المفعلة تشير إلى حسابات غير متاحة. عدّل المحقق والمراجع ومستلم التصعيد لتشغيل الأتمتة.',
 'The last workflow check failed. Check the API service and run a workflow check again.':'فشل آخر فحص لسير العمل. تحقق من خدمة API ثم أعد تشغيل الفحص.',
 'The workflow runner is starting. Refresh shortly to check its status.':'جارٍ بدء تشغيل فحوصات سير العمل. حدّث الصفحة بعد قليل للتحقق من الحالة.',
 'The workflow runner is stopped. Restart the TestAPI to resume scheduled checks.':'فحوصات سير العمل متوقفة. أعد تشغيل API الخاص بـ ExtSecure لاستئناف الفحوصات المجدولة.',
 'Escalation is ready for linked cases. Enable automatic case creation in a rule to assign new scans.':'التصعيد جاهز للحالات المرتبطة. فعّل إنشاء الحالات تلقائيًا في إحدى القواعد لإسناد الفحوصات الجديدة.',
 'Some enabled rules reference unavailable accounts and cannot create automatic cases. Review their recipients.':'بعض القواعد المفعلة تشير إلى حسابات غير متاحة ولا تستطيع إنشاء حالات تلقائية. راجع المستلمين.',
 'enabled rules':'قواعد مفعلة',
 'automatic case rules':'قواعد إنشاء الحالات تلقائيًا',
 'unread notifications':'إشعارات غير مقروءة',
 'Refresh notifications':'تحديث الإشعارات',
 'Acknowledge to mark a notification as read. Open its case to investigate or record resolution.':'أكّد الإشعار لتحديده كمقروء. افتح الحالة للتحقيق أو تسجيل الحل.',
 'No workflow notifications yet. Notifications appear when a rule assigns a new case, requests a review or escalates an unresolved case.':'لا توجد إشعارات لسير العمل بعد. تظهر الإشعارات عندما تُسند قاعدة حالة جديدة أو تطلب مراجعة أو تصعّد حالة لم تُحل.',
 'Incident assigned':'تم إسناد الحالة',
 'Review requested':'مراجعة مطلوبة',
 'Incident escalated':'تم تصعيد الحالة',
 'How automation works':'كيف تعمل الأتمتة',
 'Rules apply to new scans after they are enabled. Old scans are not turned into cases automatically. A 24-hour escalation needs an unresolved case to reach its deadline; it is not immediate.':'تُطبق القواعد على الفحوصات الجديدة بعد تفعيلها. لا تتحول الفحوصات القديمة إلى حالات تلقائيًا. يتطلب التصعيد بعد 24 ساعة وصول الحالة غير المحلولة إلى موعدها؛ ولا يحدث فورًا.',
 'Update the extension connection':'تحديث اتصال الإضافة',
 'Console version':'إصدار لوحة التحكم',
 'Worker version':'إصدار عامل الإضافة',
 'ExtSecure needs to restart to load the updated worker. Click Restart ExtSecure, close this tab, then reopen the console from the extension icon and sign in.':'تحتاج ExtSecure إلى إعادة تشغيل لتحميل التحديث. اضغط على إعادة تشغيل ExtSecure، وأغلق لوحة التحكم، ثم افتحها من أيقونة الإضافة وسجل الدخول.',
 'After restarting, close this tab and reopen the console from the ExtSecure icon. Sign in again if prompted.':'بعد إعادة التشغيل، أغلق علامة التبويب وافتح لوحة التحكم من أيقونة ExtSecure. سجل الدخول مجددًا إذا طُلب منك ذلك.',

 'Workflow automation':'أتمتة إجراءات الأمن','Control effectiveness':'فعالية الضوابط الأمنية',
 'Assign new incidents, notify reviewers and escalate unresolved cases.':'تعيين الحوادث الجديدة وإشعار المراجعين وتصعيد الحالات غير المحسومة.',
 'Measure response times and review blocking, approvals, exceptions and alerts.':'قياس أوقات الاستجابة ومراجعة الحظر والموافقات والاستثناءات والتنبيهات.',
 'Review notifications':'إشعارات المراجعة','Acknowledge':'تأكيد الاستلام','Acknowledged':'تم تأكيد الاستلام','Open case':'فتح الحالة',
 'Automation rules':'قواعد الأتمتة','Rule':'القاعدة','Rule name':'اسم القاعدة','Priority':'الأولوية','Minimum risk':'الحد الأدنى للخطورة','Investigator':'المحقق','Reviewer':'المراجع',
 'Escalate after':'التصعيد بعد','Escalate to':'التصعيد إلى','Enabled':'مفعلة','Disabled':'معطلة',
 'Create a workflow rule':'إنشاء قاعدة أتمتة','Create workflow rule':'إنشاء القاعدة','Edit a workflow rule':'تعديل قاعدة أتمتة','Save workflow rule':'حفظ القاعدة',
 'Check unresolved cases now':'فحص الحالات غير المحسومة الآن','Run workflow check':'تشغيل فحص الأتمتة',
 'Enable this workflow rule':'تفعيل قاعدة الأتمتة','Priority (lower runs first)':'الأولوية (الرقم الأقل ينفذ أولاً)',
 'Minimum risk level':'الحد الأدنى لمستوى الخطورة','Scan type':'نوع الفحص','All scan types':'جميع أنواع الفحص','Website':'موقع إلكتروني','File':'ملف',
 'Create incident cases automatically for new matching scans':'إنشاء حالات تلقائياً للفحوص الجديدة المطابقة','Assign new cases to':'تعيين الحالات الجديدة إلى',
 'Notify the reviewer in the extension':'إشعار المراجع داخل الإضافة','Escalate unresolved cases after (hours)':'تصعيد الحالات غير المحسومة بعد (ساعات)',
 'Escalate to administrator':'التصعيد إلى مسؤول','Approve an investigator account before creating a workflow rule.':'اعتمد حساب محقق قبل إنشاء قاعدة أتمتة.',
 'Assignment, review and escalation notifications stay in the extension. Acknowledging a notification does not resolve its incident.':'تُحفظ إشعارات التعيين والمراجعة والتصعيد داخل الإضافة. تأكيد الاستلام لا يحسم الحادث.',
 'The first enabled matching rule assigns each new case. Exceptions and Unknown results do not create automatic cases. Existing manually assigned cases keep their investigator until escalation. Notes do not reset the deadline; reopening starts a new deadline.':'تُعيّن أول قاعدة مفعلة ومطابقة كل حالة جديدة. لا تنشئ الاستثناءات والنتائج غير المعروفة حالات تلقائية. تحتفظ الحالات المعينة يدوياً بالمحقق حتى التصعيد. لا تعيد الملاحظات ضبط الموعد؛ وتبدأ مهلة جديدة عند إعادة فتح الحالة.',
 'Security control effectiveness':'فعالية الضوابط الأمنية','Review period':'فترة المراجعة','Last 7 days':'آخر ٧ أيام','Last 30 days':'آخر ٣٠ يوماً','Last 90 days':'آخر ٩٠ يوماً','Last 365 days':'آخر ٣٦٥ يوماً',
 'Blocked navigation reports':'بلاغات التصفح المحظور','Reported by signed-in extensions':'أبلغت عنها إضافات مسجلة الدخول','Unresolved incidents':'الحوادث غير المحسومة','Created in this review period':'المنشأة خلال فترة المراجعة',
 'Repeated detections':'الاكتشافات المتكررة','Same target and device':'الهدف والجهاز نفسيهما','Control':'الضابط','Reviewed':'تمت مراجعته','Effective':'فعال','Missed':'فائت','Unnecessary':'غير ضروري','Inconclusive':'غير حاسم','Effectiveness':'الفعالية','Not assessed':'لم يتم تقييمه',
 'Approval response':'الاستجابة للموافقة','Alert response':'الاستجابة للتنبيه','Incident resolution':'حسم الحادث','Response time':'وقت الاستجابة','Samples':'العينات','Median':'الوسيط','95th percentile':'المئين ٩٥','Recorded activity':'النشاط المسجل',
 'Missed warnings':'التحذيرات الفائتة','Unnecessary warnings':'التحذيرات غير الضرورية','Labelled scans':'الفحوص المصنفة','Reviewer-labelled threats below High':'تهديدات صنفها المراجع دون مستوى مرتفع','Reviewer-labelled benign High/Critical scans':'فحوص مرتفعة أو حرجة صنفها المراجع سليمة',
 'Evidence reviews':'مراجعات الأدلة','Record a control assessment':'تسجيل تقييم ضابط','Recorded evidence':'الأدلة المسجلة','Observed outcome':'النتيجة الملحوظة','Independent threat label':'التصنيف المستقل للتهديد',
 'Not independently verified':'لم يُتحقق منه بشكل مستقل','Verified threat':'تهديد متحقق منه','Verified benign':'سليم متحقق منه','Evidence and reasoning':'الأدلة والمبررات','Record assessment':'تسجيل التقييم','Outcome':'النتيجة','Label':'التصنيف','Reference':'المرجع','Reviewed by':'راجعه',
 'blocking':'الحظر','approvals':'الموافقات','exceptions':'الاستثناءات','alerts':'التنبيهات','effective':'فعال','missed':'فائت','unnecessary':'غير ضروري','inconclusive':'غير حاسم',
 'assigned':'تم التعيين','review_requested':'طُلبت المراجعة','escalated':'تم التصعيد','threat':'تهديد','benign':'سليم','unknown':'غير معروف',
 'Record a verified outcome and the evidence supporting it. Keep private URLs, personal details and credentials out of notes. A review never changes a score or an approval.':'سجّل نتيجة متحققاً منها والأدلة الداعمة لها. تجنب الروابط الخاصة والبيانات الشخصية وبيانات الدخول في الملاحظات. لا تغير المراجعة درجة الخطورة أو الموافقة.',
 'Table size':'حجم الجدول','Compact':'مضغوط','Standard':'قياسي','Spacious':'موسع','Table size saved.':'تم حفظ حجم الجدول.',
 'Choose a supported table size.':'اختر حجماً مدعوماً للجدول.',
 'Device':'الجهاز','User':'المستخدم','Website / file':'الموقع / الملف','Not recorded':'غير مسجل',
 'Profile logo':'صورة الحساب','Choose profile logo':'اختر صورة الحساب','Save logo':'حفظ الصورة','Remove logo':'إزالة الصورة',
 'Profile logo saved.':'تم حفظ صورة الحساب.','Profile logo removed.':'تمت إزالة صورة الحساب.',
 'Your logo is saved for this account in this Chrome profile only.':'تُحفظ الصورة لهذا الحساب في ملف Chrome الحالي فقط.',
 'PNG, JPG or WebP · up to 2 MiB. The image is cropped to a square and resized before saving.':'PNG أو JPG أو WebP بحجم لا يتجاوز 2 ميبيبايت. تُقص الصورة إلى مربع ويُغيّر حجمها قبل الحفظ.',
 'Choose an image first.':'اختر صورة أولاً.','Choose a PNG, JPG or WebP image.':'اختر صورة بصيغة PNG أو JPG أو WebP.',
 'Choose an image of 2 MiB or less.':'اختر صورة بحجم لا يتجاوز 2 ميبيبايت.',
 'This image could not be opened. Choose another image.':'تعذر فتح هذه الصورة. اختر صورة أخرى.',
 'Choose an image no larger than 4096 pixels on either side.':'اختر صورة لا يتجاوز أي من أبعادها 4096 بكسل.',

 'Personalize the extension appearance, language and display times.':'خصص مظهر الإضافة ولغتها وتوقيت عرض البيانات.',
 'Dark mode':'الوضع الداكن',
 'Appearance':'المظهر','Light':'فاتح','Dark':'داكن','Use device setting':'استخدام إعداد الجهاز','Appearance, language and time':'المظهر واللغة والوقت','Choose a supported appearance.':'اختر مظهراً مدعوماً.',
 'Each saved snapshot includes every alert and AI explanation recorded during that period, plus an aggregate narrative. The downloadable archive contains all rows; identifiers and raw content are excluded from the model prompt.':'يتضمن كل تقرير محفوظ جميع التنبيهات وتوضيحات الذكاء الاصطناعي المسجلة خلال الفترة، بالإضافة إلى ملخص مجمّع. يحتوي الأرشيف القابل للتنزيل على جميع السجلات، وتُستبعد المعرّفات والمحتوى الخام من المدخلات المرسلة إلى النموذج.',
 'Connected':'متصل','Connection details':'تفاصيل الاتصال','Only enabled extension IDs, names and versions are synced.':'تتم مزامنة معرّفات الإضافات المفعّلة وأسمائها وإصداراتها فقط.','Completed UTC periods only. Weekly periods begin on Monday.':'التقارير للفترات المكتملة بتوقيت UTC فقط. يبدأ الأسبوع يوم الاثنين.',
 'Find a section':'البحث عن قسم','Find a section…':'ابحث عن قسم…','No matching sections':'لا توجد أقسام مطابقة','matching sections':'أقسام مطابقة','Menu':'القائمة','How access works':'كيفية إدارة الوصول','Report workspace':'مساحة التقارير','Monthly analysis and delivery':'التحليل الشهري والإرسال','Snapshot history':'سجل التقارير','Optional content for the explanation':'محتوى اختياري للتوضيح','Website stays blocked until approval.':'يبقى الموقع محظوراً حتى الموافقة.',
 'Dashboard':'لوحة التحكم','Account & settings':'الحساب والإعدادات','Scan details':'تفاصيل الفحص','Only the site origin is checked.':'يُفحص أصل الموقع فقط.','Security workspace':'لوحة الأمان','Review findings, access requests and reports.':'راجع النتائج وطلبات الوصول والتقارير.','Alerts need your review.':'تحتاج التنبيهات إلى مراجعتك.',
 'complete':'مكتمل','partial':'جزئي','unknown':'غير معروف','pending':'قيد الانتظار','approved':'موافق عليه','rejected':'مرفوض','temporary':'مؤقت','whitelist':'القائمة المسموحة','open':'مفتوح','resolved':'تم الحل','acknowledged':'تم الاطلاع','ready':'جاهز','active':'نشط','inactive':'غير نشط','suppressed':'مستثنى من التنبيه','unverified':'غير مؤكد','Reference':'المرجع','Head of Administrator':'رئيس المسؤولين',
 'Security workflows':'مسارات العمل الأمنية','Quick actions':'إجراءات سريعة','Check a destination':'فحص وجهة','Review reputation before proceeding.':'راجع السمعة قبل المتابعة.','Review website access':'مراجعة الوصول إلى المواقع','Keep approvals and expiry clear.':'راجع الموافقات ومدد صلاحيتها.','Investigate alerts':'التحقيق في التنبيهات','Record a decision for each threat.':'سجّل قراراً لكل تهديد.','Review reports':'مراجعة التقارير','Compare weekly and monthly evidence.':'قارن الأدلة الأسبوعية والشهرية.',
 'Check API connection':'التحقق من اتصال API','API connected':'API متصل','API unavailable':'API غير متاح','Checking API…':'جارٍ التحقق من API…','Connection and recovery':'الاتصال والاستعادة','Check the existing local API before running scans or generating reports.':'تحقق من API المحلي الحالي قبل إجراء الفحوصات أو إنشاء التقارير.',
 'Run Start ExtSecure.cmd from your installed project folder.':'شغّل Start ExtSecure.cmd من مجلد المشروع المثبت.','Reload ExtSecure on chrome://extensions after an update, then reopen its console.':'أعد تحميل ExtSecure من chrome://extensions بعد التحديث، ثم افتح لوحة التحكم مجدداً.','Sign in with your approved account and authenticator. Add this Chrome device if requested.':'سجّل الدخول بالحساب المعتمد وتطبيق المصادقة. أضف جهاز Chrome هذا إذا طُلب ذلك.','A connected API does not guarantee provider availability or a safe result.':'اتصال API لا يضمن توفر مزود الفحص أو أمان نتيجة الفحص.',
 'The local API is reachable. Provider checks may still be unavailable.':'يمكن الوصول إلى API المحلي. قد تبقى فحوصات المزود غير متاحة.','The API is unavailable. Run Start ExtSecure.cmd, then check again.':'API غير متاح. شغّل Start ExtSecure.cmd ثم تحقق مجدداً.','Reconnect to your workspace':'إعادة الاتصال بمساحة العمل',
 'Loading your workspace…':'جارٍ تحميل مساحة العمل…','Risk assessment':'تقييم الخطورة','No usable evidence was available for this assessment. Unknown is not a safe result.':'لم تتوفر أدلة صالحة لهذا التقييم. لا تعني نتيجة «غير معروف» أن العنصر آمن.','The score reflects confirmed rules and available evidence. Low does not guarantee safety.':'تعكس الدرجة القواعد المؤكدة والأدلة المتاحة. الخطورة المنخفضة لا تضمن الأمان.','Download scan evidence':'تنزيل أدلة الفحص','Open evidence workspace':'فتح مساحة الأدلة','records returned':'سجلات مسترجعة','matching records':'سجلات مطابقة','No matching results':'لا توجد نتائج مطابقة','Change the search text to see more recorded results.':'غيّر نص البحث لرؤية المزيد من النتائج المسجلة.','Filtering searches only the records returned in this view.':'يشمل البحث السجلات المسترجعة في هذا العرض فقط.',
 'AI reporting is unavailable. Check the configured local model or provider settings on the backend.':'تقارير الذكاء الاصطناعي غير متاحة. تحقق من النموذج المحلي المهيأ أو إعدادات المزود في الخادم.','Choose a completed week beginning on Monday in UTC.':'اختر أسبوعاً مكتملاً يبدأ يوم الاثنين بتوقيت UTC.','Confirm optional content sharing before submitting a page or text file.':'أكد الموافقة على مشاركة المحتوى الاختياري قبل إرسال صفحة أو ملف نصي.',
 'The hash lookup ran, but VirusTotal has no report for this file. File contents were not uploaded. Unknown means there is not enough reputation evidence; it does not mean safe.':'تم الاستعلام عن بصمة الملف، لكن لا يوجد تقرير عنه في VirusTotal. لم يتم رفع محتوى الملف. تعني «غير معروف» أن الأدلة المتاحة غير كافية، ولا تعني أن الملف آمن.',
 'File reputation checks are unavailable because the existing backend provider is not configured. Ask the backend owner to check VirusTotal settings.':'فحص سمعة الملفات غير متاح لأن مزود الخدمة غير مهيأ في الخادم. اطلب من مسؤول الخادم التحقق من إعدادات VirusTotal.',
 'VirusTotal rejected the backend credentials. Ask the backend owner to check the existing API key.':'رفض VirusTotal بيانات اعتماد الخادم. اطلب من مسؤول الخادم التحقق من مفتاح API الحالي.',
 'The reputation lookup reached a request limit. Wait for the retry period before checking again.':'وصل فحص السمعة إلى حد الطلبات المسموح به. انتظر مدة إعادة المحاولة قبل إجراء الفحص مجدداً.',
 'The reputation provider could not be reached or did not return a successful report. Retry later; no safe verdict was assigned.':'تعذر الوصول إلى مزود السمعة أو الحصول على تقرير ناجح. أعد المحاولة لاحقاً؛ لم يُصنّف العنصر بأنه آمن.',
 'The provider returned an incomplete or invalid analysis. The risk result stays Unknown until usable evidence is available.':'أعاد المزود تحليلاً غير مكتمل أو غير صالح. تبقى نتيجة الخطورة «غير معروف» حتى تتوفر أدلة صالحة.',
 'No usable reputation evidence was returned. Retry the check or investigate through an approved method; Unknown is not a safe result.':'لم تتوفر أدلة سمعة صالحة. أعد الفحص أو تحقق بطريقة معتمدة؛ نتيجة «غير معروف» لا تعني أن العنصر آمن.',
 'The file hash reputation lookup completed. Review the risk result and recorded detections; Low does not guarantee safety.':'اكتمل فحص سمعة بصمة الملف. راجع مستوى الخطورة ونتائج الكشف المسجلة؛ الخطورة المنخفضة لا تضمن الأمان.',
 'The website reputation lookup completed. The risk result reflects the returned evidence.':'اكتمل فحص سمعة الموقع. تعكس نتيجة الخطورة الأدلة التي أعادها المزود.',
 'Retry after':'أعد المحاولة بعد','seconds.':'ثانية.','Cached reputation result':'نتيجة سمعة محفوظة مؤقتاً',
 'Review weekly and monthly reports, aggregate statistics and machine-learning evidence.':'مراجعة التقارير الأسبوعية والشهرية والإحصاءات المجمعة وأدلة التعلم الآلي',
 'Device access before adding':'وصول الجهاز قبل إضافته','Choose device access':'اختر وصول الجهاز','Trusted device':'جهاز موثوق','Blocked device':'جهاز محظور',
 'Choose Trusted device or Blocked device before adding this device.':'اختر جهازاً موثوقاً أو جهازاً محظوراً قبل إضافة هذا الجهاز.',
 'Trusted device allows ExtSecure activity. Blocked device records this device but denies scans and website access until an administrator allows it.':'الجهاز الموثوق يسمح بنشاط ExtSecure. يُسجّل الجهاز المحظور لكن يُمنع من الفحص والوصول إلى المواقع حتى يسمح له المسؤول.',
 'Trusted device requests administrator approval. Blocked device records this device with access denied until an administrator allows it.':'اختيار جهاز موثوق يطلب موافقة المسؤول. يُسجّل الجهاز المحظور مع منع الوصول حتى يسمح له المسؤول.',
 'Device added as blocked. An administrator must allow it before scans or website access.':'أُضيف الجهاز بوصفه محظوراً. يجب أن يسمح له المسؤول قبل الفحص أو الوصول إلى المواقع.',
 'Update the Chrome connection':'تحديث ربط Chrome',
 'Chrome is running an older ExtSecure worker. Restart the extension to enable device and extension connection.':'يشغّل Chrome إصداراً قديماً من خدمة ExtSecure الخلفية. أعد تشغيل الإضافة لتفعيل ربط الجهاز والإضافات.',
 'Restart ExtSecure':'إعادة تشغيل ExtSecure',
 'After restarting, close this console tab, reopen ExtSecure from the Chrome extension icon and sign in. Device records stay saved.':'بعد إعادة التشغيل، أغلق علامة تبويب لوحة التحكم وافتح ExtSecure من أيقونة الإضافة في Chrome ثم سجّل الدخول. تبقى سجلات الأجهزة محفوظة.',
 'Add this device registers this Chrome profile and ExtSecure first. Then click Connect enabled Chrome extensions and allow Chrome\'s permission prompt to include the other enabled extensions. The operating system is detected automatically.':'أضف هذا الجهاز لتسجيل ملف Chrome وإضافة ExtSecure أولاً. ثم اضغط ربط إضافات Chrome المفعّلة واسمح بطلب الإذن لإضافة بقية الإضافات. يُكتشف نظام التشغيل تلقائياً.',
 'Device connected. Click Connect enabled Chrome extensions to include the other extensions.':'تم ربط الجهاز. اضغط ربط إضافات Chrome المفعّلة لإضافة بقية الإضافات.',
 'Chrome inventory permission was not granted. Your device remains connected. Click Connect enabled Chrome extensions to try again.':'لم يُمنح إذن جرد إضافات Chrome. يبقى جهازك مرتبطاً. اضغط ربط إضافات Chrome المفعّلة لإعادة المحاولة.',
 'Chrome inventory permission is unavailable. Reload ExtSecure and reopen its console.':'إذن جرد إضافات Chrome غير متاح. أعد تحميل ExtSecure وافتح لوحة التحكم مجدداً.',
 'Add this device':'إضافة هذا الجهاز','Refresh devices & extensions':'تحديث الأجهزة والإضافات','Device & Chrome connection':'ربط الجهاز وإضافات Chrome','Optional device details':'تفاصيل الجهاز الاختيارية','Device name (optional)':'اسم الجهاز (اختياري)','IP address (optional)':'عنوان IP (اختياري)','Automatically named':'يُسمّى تلقائياً','Enter a LAN IP if needed':'أدخل عنوان الشبكة المحلية عند الحاجة','Pending approval':'بانتظار الموافقة','Requested by':'طلبه','Not provided':'غير متوفر','Entered IP':'عنوان مُدخل','Connection IP':'عنوان الاتصال','Allow device':'السماح للجهاز','Check approval status':'التحقق من الموافقة','Older scan records':'سجلات الفحص السابقة','Advanced connection recovery':'استعادة الربط المتقدمة','Existing device connection (advanced)':'ربط جهاز موجود (متقدم)',
 'Device added. Waiting for administrator approval.':'تمت إضافة الجهاز. بانتظار موافقة المسؤول.',
 'This Chrome profile is connected.':'تم ربط ملف Chrome هذا.',
 'Add this device to connect Chrome inventory automatically.':'أضف هذا الجهاز لربط جرد Chrome تلقائياً.',
 'The operating system is detected automatically. Chrome asks permission to list enabled extensions. If permission is declined, the device is still added and only ExtSecure is listed.':'يُكتشف نظام التشغيل تلقائياً. يطلب Chrome الإذن بعرض الإضافات المفعّلة. إذا رُفض الإذن، يظل الجهاز مضافاً وتُعرض ExtSecure فقط.',
 "IP is optional. Localhost is not saved as your computer's LAN address. Only enabled extension IDs, names and versions are synced.":'عنوان IP اختياري. لا يُحفظ عنوان الخادم المحلي باعتباره عنوان حاسوبك على الشبكة المحلية. تُزامن معرّفات الإضافات المفعّلة وأسماؤها وإصداراتها فقط.',
 'Load ExtSecure in Chrome to add this device.':'حمّل ExtSecure في Chrome لإضافة هذا الجهاز.',
 'Allow device approves a pending request or unblocks a device. Block device denies ExtSecure scans and website approvals.':'السماح للجهاز يعتمد الطلب المعلّق أو يلغي حظر الجهاز. حظر الجهاز يمنع فحوص ExtSecure والموافقة على زيارة المواقع.',
 'Device connected. Click Refresh devices & extensions to retry inventory sync.':'تم ربط الجهاز. اضغط تحديث الأجهزة والإضافات لإعادة محاولة مزامنة الجرد.',
 'Device connected. Allow Chrome inventory permission to list other extensions.':'تم ربط الجهاز. امنح إذن جرد Chrome لعرض الإضافات الأخرى.',
 'Click Add this device in My account to continue.':'اضغط إضافة هذا الجهاز في حسابي للمتابعة.',

 'Add device':'إضافة جهاز','Device inventory':'جرد الأجهزة','Blocked devices':'الأجهزة المحظورة','Active devices':'الأجهزة النشطة','All devices':'جميع الأجهزة','Show devices':'عرض الأجهزة','IP address':'عنوان IP','Operating system':'نظام التشغيل','Detected OS':'نظام التشغيل الذي اكتشفه Chrome','Device name':'اسم الجهاز','Registered devices':'الأجهزة المسجلة','Linked Chrome profiles':'ملفات Chrome المرتبطة','Manage device access':'إدارة وصول الجهاز','Device access':'وصول الجهاز','Block device':'حظر الجهاز','Unblock device':'إلغاء حظر الجهاز','Save device access':'حفظ وصول الجهاز','Issue new pairing code':'إصدار رمز ربط جديد','One-time pairing code':'رمز ربط للاستخدام مرة واحدة','One-time device pairing code':'رمز ربط الجهاز للاستخدام مرة واحدة','Chrome device connection':'ربط جهاز Chrome','Link this Chrome profile':'ربط ملف Chrome هذا','Connect enabled Chrome extensions':'ربط إضافات Chrome المفعّلة','Chrome enabled extension inventory':'جرد إضافات Chrome المفعّلة','Chrome extension ID':'معرّف إضافة Chrome','Last inventory sync':'آخر مزامنة للجرد','Last sync':'آخر مزامنة','Source':'المصدر','Enabled':'مفعّلة','Blocked':'محظور','Active':'نشط','Awaiting pairing':'بانتظار الربط','Unverified':'غير متحقق منها','Not in latest snapshot':'غير موجودة في آخر مزامنة','Scan record':'سجل فحص','Chrome inventory':'جرد Chrome','Open My account':'فتح حسابي','Open device inventory':'فتح جرد الأجهزة',
 'Only enabled extension IDs, names and versions are synced. Website content, browsing history and extension permissions are not collected by inventory sync.':'تُزامن معرّفات الإضافات المفعّلة وأسماؤها وإصداراتها فقط. لا تجمع مزامنة الجرد محتوى المواقع أو سجل التصفح أو صلاحيات الإضافات.',
 'This device is blocked. An administrator must unblock it before scans or website access can continue.':'هذا الجهاز محظور. يجب على المسؤول إلغاء الحظر قبل متابعة الفحص أو الوصول إلى المواقع.',
 'Device enrollment is required. Ask an administrator for a one-time pairing code.':'تسجيل الجهاز مطلوب. اطلب من المسؤول رمز ربط للاستخدام مرة واحدة.',
 'Link this Chrome profile to a device to connect the inventory.':'اربط ملف Chrome هذا بجهاز لربطه بالجرد.',
 'Adding the first device requires device enrollment for scans and website access. Pair this browser to continue.':'عند إضافة أول جهاز يصبح ربط الأجهزة مطلوباً للفحص والوصول إلى المواقع. اربط هذا المتصفح للمتابعة.',
 'Chrome inventory requires loading the extension.':'يتطلب جرد Chrome تحميل الإضافة.',
 'Chrome inventory permission was not granted.':'لم يتم منح إذن جرد إضافات Chrome.',
 'This device is blocked. Contact an administrator.':'هذا الجهاز محظور. تواصل مع المسؤول.',
 'Link this Chrome profile to a registered device before continuing.':'اربط ملف Chrome هذا بجهاز مسجل قبل المتابعة.',

 'Permanent website whitelist':'القائمة الدائمة للمواقع المسموحة',
 'Forever website approvals appear here and in Website access. Revoking an entry updates both views. Website access approval does not suppress threat alerts or change risk scores.':'تظهر الموافقات الدائمة هنا وفي الوصول للمواقع. ينعكس إلغاء السماح في العرضين. لا تخفي موافقة الوصول تنبيهات التهديدات ولا تغير درجات الخطورة.',
 'This URL is already approved. No new request is needed.':'تمت الموافقة على هذا الرابط مسبقاً. لا حاجة إلى طلب جديد.',
 'Approval duration':'مدة الموافقة','24 hours':'24 ساعة','7 days':'7 أيام','Forever (whitelist)':'دائم (القائمة المسموحة)','Forever':'دائم','Approve request':'الموافقة على الطلب',
 'Temporary approval allows repeat visits for 24 hours or 7 days. After expiry, request access again. Forever adds the URL to the shared whitelist until revoked.':'تسمح الموافقة المؤقتة بزيارات متكررة لمدة 24 ساعة أو 7 أيام. بعد انتهائها، اطلب الوصول مجدداً. تضيف الموافقة الدائمة الرابط إلى القائمة المشتركة حتى إلغاء السماح.',
 'You may review your own request. Submit it, then open the approval queue.':'يمكنك مراجعة طلبك الخاص. أرسله ثم افتح قائمة طلبات الموافقة.',
 'Waiting for approval by a higher role.':'بانتظار موافقة الدور الأعلى.',
 'Requested role':'الدور المطلوب',
 'Users need a manager, managers need an administrator, and administrators need the head. The head may review their own requests.':'يحتاج المستخدم إلى موافقة مدير، والمدير إلى مسؤول، والمسؤول إلى رئيس المسؤولين. يمكن للرئيس مراجعة طلباته الخاصة.',
 'Approval pyramid: normal users → managers → administrators → head administrator. Higher roles may approve lower roles. Only the head changes existing account privileges. Every account requires 2FA.':'تسلسل الموافقة: المستخدمون ← المديرون ← المسؤولون ← رئيس المسؤولين. يمكن للدور الأعلى اعتماد الأدوار الأقل. يغير الرئيس وحده صلاحيات الحسابات الحالية. المصادقة الثنائية مطلوبة للجميع.',
 'Access requires approval by a higher role.':'يتطلب الوصول موافقة دور أعلى.',
 'Account verified. A higher role must approve access before you can sign in.':'تم التحقق من الحساب. يجب أن يعتمد دور أعلى وصولك قبل تسجيل الدخول.',
 'Select your requested role at the authenticator step. A higher role must approve it.':'اختر دورك المطلوب في خطوة المصادقة. يجب أن يعتمد الدور الأعلى طلبك.',

 'Browser security':'أمان التصفح','Overview':'نظرة عامة','Scan a page':'فحص صفحة','Alerts':'التنبيهات','Findings':'نتائج الفحص','Risk levels':'مستويات الخطورة','Downloaded-file checks':'فحص الملفات المحمّلة','File checks':'فحص الملفات','Scan history':'سجل الفحص','Devices':'الأجهزة','Extensions':'الإضافات','Security events':'الأحداث الأمنية','Incident cases':'الحوادث الأمنية','Whitelist & overrides':'الاستثناءات الأمنية','Reports':'التقارير','Security policies':'السياسات الأمنية','Privacy governance':'حوكمة الخصوصية','Detection evaluation':'تقييم جودة الكشف','Usability and accessibility':'سهولة الاستخدام وإمكانية الوصول','Usability & accessibility':'سهولة الاستخدام وإمكانية الوصول','Accounts':'الحسابات','Security guidance':'الإرشادات الأمنية','My account':'حسابي','My file history':'سجل فحوصاتي','Website access':'صلاحيات المواقع','Settings':'الإعدادات',
 'Monitor':'المراقبة','Inventory':'المخزون','Investigate':'التحقيق','Govern':'الإدارة','Support':'الدعم','Extension console':'لوحة الإضافة','Extension navigation':'التنقل في الإضافة','Sign out':'تسجيل الخروج','Refresh':'تحديث','2FA verified':'تم التحقق بخطوتين','Head of Administrator':'رئيس المسؤولين','Administrator':'مسؤول النظام','Manager':'مدير','Normal user':'مستخدم عادي',
 'Low':'منخفض','Medium':'متوسط','High':'مرتفع','Critical':'حرج','Unknown':'غير معروف','pending':'قيد الانتظار','approved':'موافق عليه','rejected':'مرفوض','consumed':'تم استخدامه','open':'مفتوح','acknowledged':'تمت المراجعة','resolved':'تم الحل','investigating':'قيد التحقيق','once':'زيارة واحدة','whitelist':'القائمة المسموحة',
 'Welcome to ExtSecure':'مرحباً بك في ExtSecure','Create your account':'إنشاء حساب','Log in':'تسجيل الدخول','Register account':'إنشاء حساب جديد','Username':'اسم المستخدم','Password':'كلمة المرور','Confirm password':'تأكيد كلمة المرور','Continue securely':'متابعة آمنة','Verify it’s you':'التحقق من هويتك','Six-digit authenticator code':'رمز تطبيق المصادقة المكوّن من ستة أرقام','Verify and sign in':'تحقق وسجّل الدخول','Start sign-in again':'بدء تسجيل الدخول مجدداً','Your credentials':'بيانات الدخول','Account details':'بيانات الحساب','Set up authenticator':'إعداد تطبيق المصادقة','Set up your authenticator':'إعداد تطبيق المصادقة','Authenticator enrollment':'ربط تطبيق المصادقة','Verify account':'التحقق من الحساب','Cancel registration':'إلغاء التسجيل','Enter the setup key manually':'إدخال مفتاح الإعداد يدوياً','Password accepted · Authenticator required':'تم قبول كلمة المرور · يلزم رمز المصادقة','No invitation code required.':'لا يلزم رمز دعوة.',
 'Sign in to your approved account to review browser security.':'سجّل الدخول إلى حسابك المعتمد لمراجعة أمان التصفح.','Use the current code from your authenticator app to complete sign-in.':'أدخل الرمز الحالي من تطبيق المصادقة لإكمال تسجيل الدخول.','The backend verifies both steps before granting access.':'يتحقق الخادم من الخطوتين قبل منح الوصول.','Scan the QR code in your authenticator app, then verify a six-digit code.':'امسح رمز QR في تطبيق المصادقة، ثم أدخل رمز التحقق المكوّن من ستة أرقام.','Set up an account and authenticator, then request administrator approval.':'أنشئ حساباً واربط تطبيق المصادقة، ثم اطلب موافقة المسؤول.','New accounts need approval. Every role uses password and authenticator verification.':'تحتاج الحسابات الجديدة إلى موافقة. تتطلب جميع الأدوار كلمة مرور ورمز مصادقة.','Setup expires after 15 minutes. Access requires approval by the Head of Administrator.':'تنتهي صلاحية الإعداد بعد 15 دقيقة. يلزم الحصول على موافقة رئيس المسؤولين للوصول.','Choose at least 12 characters. The main administrator assigns your role after approval.':'اختر كلمة مرور من 12 حرفاً على الأقل. يحدد المسؤول الرئيسي دورك بعد الموافقة.',
 'A calmer view of browser security':'رؤية أوضح لأمان التصفح','Clear signals.':'مؤشرات واضحة.','Confident decisions.':'قرارات مدروسة.','Check destinations, investigate threats and keep the evidence together in your browser.':'افحص المواقع، وحقق في التهديدات، واحتفظ بالأدلة في لوحة المتصفح.','Approved accounts. Two required sign-in steps.':'حسابات معتمدة وخطوتان إلزاميتان لتسجيل الدخول.','Local file hashing. Backend-owned risk scores.':'حساب بصمة الملف محلياً وتقييم الخطورة على الخادم.',
 'Language and time zone':'اللغة والمنطقة الزمنية','Language':'اللغة','Time zone':'المنطقة الزمنية','Save preferences':'حفظ التفضيلات','Preferences saved.':'تم حفظ التفضيلات.','Choose a supported language and time zone.':'اختر لغة ومنطقة زمنية مدعومتين.','Arabic and English are supported. Times follow your selected zone; monthly report boundaries stay in UTC.':'تتوفر العربية والإنجليزية. تُعرض الأوقات وفق المنطقة المحددة، وتبقى حدود التقارير الشهرية حسب UTC.','These settings apply to the popup, console and blocked-page screen.':'تُطبق هذه الإعدادات على النافذة المنبثقة ولوحة الإضافة وصفحة حظر المواقع.','Recorded evidence and administrator notes keep their original language.':'تُعرض الأدلة المسجلة وملاحظات المسؤولين بلغتها الأصلية.','Saudi Arabia / KSA · UTC+3':'السعودية · UTC+3','United Arab Emirates · UTC+4':'الإمارات العربية المتحدة · UTC+4','Bahrain · UTC+3':'البحرين · UTC+3','United Kingdom':'المملكة المتحدة','Central Europe':'وسط أوروبا','New York':'نيويورك','India':'الهند','Japan':'اليابان',
 'Website approval required':'يلزم اعتماد الموقع','This website is blocked':'هذا الموقع محظور','Request access':'طلب الوصول','Open approved website':'فتح الموقع المعتمد','Check approval':'التحقق من الموافقة','Open approval queue':'فتح قائمة الطلبات','Sign in to request access':'سجّل الدخول لطلب الوصول','Destination':'الموقع المطلوب','Request reason':'سبب الطلب','Review request':'مراجعة الطلب','Approve one visit':'الموافقة على زيارة واحدة','Approve URL whitelist':'إضافة الرابط للقائمة المسموحة','Reject request':'رفض الطلب','Decision':'القرار','Decision reason':'سبب القرار','Whitelist duration (days)':'مدة السماح بالأيام','Submit decision':'حفظ القرار','Revoke whitelist entry':'إلغاء السماح بالرابط','Revoke access':'إلغاء السماح','Approved URL whitelist':'روابط المواقع المسموحة','Access requests':'طلبات الوصول','Requester':'مقدم الطلب','Requested':'تاريخ الطلب','Reviewed by':'راجعه','Expires':'تنتهي الصلاحية','Status':'الحالة','Reason':'السبب','URL':'الرابط','Select request':'اختر الطلب','Select whitelist entry':'اختر الرابط المسموح','No pending requests':'لا توجد طلبات قيد الانتظار','Visit approval is ready.':'تمت الموافقة على الزيارة.','Waiting for manager or administrator approval.':'بانتظار موافقة مدير أو مسؤول النظام.','The website stays blocked until an approved visit is opened.':'يبقى الموقع محظوراً حتى فتح زيارة معتمدة.','A one-visit approval expires after 10 minutes and is used once. A whitelist approval is reusable by approved accounts until expiry or revocation.':'تنتهي موافقة الزيارة الواحدة بعد 10 دقائق وتُستخدم مرة واحدة. يمكن للحسابات المعتمدة استخدام الرابط المسموح حتى انتهاء الصلاحية أو إلغاء الموافقة.','The exact scheme, host, port and path are approved. Query strings and fragments are not stored in approval requests.':'تشمل الموافقة البروتوكول والمضيف والمنفذ والمسار المحدد. لا تُحفظ معاملات الاستعلام أو أجزاء الرابط في الطلبات.','Another manager or administrator must review your own request':'يجب أن يراجع مدير أو مسؤول آخر طلبك.','Access request sent. The website remains blocked until approval.':'تم إرسال الطلب. يبقى الموقع محظوراً إلى حين الموافقة.','Confirm you have reviewed the destination and the business need.':'أؤكد مراجعة الموقع المطلوب وسبب الحاجة إليه.','Add the URL and explain why access is needed.':'أدخل الرابط واشرح سبب حاجتك إلى الوصول.','Requests and whitelist decisions are recorded for audit.':'تُسجل طلبات الوصول وقرارات السماح لأغراض التدقيق.','Managing website approval does not change risk scores or suppress threat alerts.':'لا تغير الموافقة على المواقع درجات الخطورة ولا توقف تنبيهات التهديدات.','Sign in':'تسجيل الدخول','Return to safety':'العودة إلى صفحة آمنة','Close this tab':'إغلاق هذه الصفحة',
 'Save change':'حفظ التغيير','No records yet':'لا توجد سجلات بعد','Nothing to review':'لا توجد نتائج للمراجعة','No records are available for this selection.':'لا توجد سجلات لهذا الاختيار.','Recorded results':'النتائج المسجلة','Loading your workspace…':'جارٍ تحميل اللوحة…','Try again':'حاول مجدداً','View all':'عرض الكل','Check a page':'فحص صفحة','Check a downloaded file':'فحص ملف محمّل','Check current destination':'فحص الموقع الحالي','Open console':'فتح لوحة الإضافة','Security posture':'الحالة الأمنية','Risk distribution':'توزيع الخطورة','Activity over 14 days':'النشاط خلال 14 يوماً','Recent security events':'الأحداث الأمنية الأخيرة','All time':'كل الفترات','All scans':'جميع الفحوصات','High / Critical':'مرتفع / حرج','Total scans':'إجمالي الفحوصات','Awaiting review':'بانتظار المراجعة','Devices seen':'الأجهزة المسجلة','Keep the next action clear':'حدد الخطوة التالية بوضوح','Check a download':'فحص ملف محمّل','Investigate with evidence':'التحقيق بالاستناد إلى الأدلة','Read security guidance':'قراءة الإرشادات الأمنية','Your workspace is ready.':'اللوحة جاهزة.','Review the signals that need you.':'راجع المؤشرات التي تحتاج إلى اهتمامك.','Hash the file in your browser. File contents stay on this device.':'احسب بصمة الملف داخل المتصفح. يبقى محتوى الملف على هذا الجهاز.','Link a finding to a case and record the decision that follows.':'اربط نتيجة الفحص بحادثة وسجل القرار المتخذ.','No recent activity':'لا يوجد نشاط حديث','New scans and security decisions will appear here.':'ستظهر هنا الفحوصات الجديدة والقرارات الأمنية.','Completed checks will appear here with their evidence and next steps.':'ستظهر الفحوصات المكتملة مع الأدلة والخطوات التالية.',
 'Score':'الدرجة','Severity':'مستوى الخطورة','Assessment':'التقييم','Time':'الوقت','Target':'الهدف','ID':'المعرّف','Evidence':'الأدلة','Next action':'الخطوة التالية','Filter records':'تصفية السجلات','Search records':'البحث في السجلات','Review':'مراجعة','Created':'تاريخ الإنشاء','Name':'الاسم','Role':'الدور','Version':'الإصدار','Last seen':'آخر ظهور','Type':'النوع','Message':'الرسالة','Actor':'المنفذ','Action':'الإجراء','Details':'التفاصيل','Back to results':'العودة إلى النتائج','Current session':'الجلسة الحالية','Session expires':'انتهاء الجلسة','Role and access':'الدور والصلاحيات','Assigned role':'الدور المحدد','Signed in as':'الحساب الحالي','Your account':'حسابك','Available workspaces':'الأقسام المتاحة','File name':'اسم الملف','File hash':'بصمة الملف','Choose a file':'اختيار ملف','SHA-256 hash':'بصمة SHA-256','Check file hash':'فحص بصمة الملف','Scan URL':'فحص الرابط','Check destination':'فحص الموقع','Include URL path':'تضمين مسار الرابط','Local hashing':'حساب البصمة محلياً','Risk result':'نتيجة الخطورة','No result yet':'لا توجد نتيجة بعد','Select a completed month':'اختر شهراً مكتملاً','Month (UTC)':'الشهر (UTC)','Monthly statistics':'الإحصاءات الشهرية','Machine learning':'التعلم الآلي','Run activity review':'تحليل النشاط','Generate AI draft':'إنشاء مسودة بالذكاء الاصطناعي','Send to administrators':'الإرسال إلى المسؤولين','Download ML evidence':'تنزيل أدلة التعلم الآلي','Unusual':'غير معتاد','Day':'اليوم','Scans':'الفحوصات','AI-written summary':'ملخص بالذكاء الاصطناعي','Report delivery':'تسليم التقرير','Create case':'إنشاء حادثة','Title':'العنوان','Assignee':'المسؤول عن الحادثة','Investigation notes':'ملاحظات التحقيق','Add note':'إضافة ملاحظة','Update case':'تحديث الحادثة','Resolution':'الحل','Review alert':'مراجعة التنبيه','Update status':'تحديث الحالة','Approved':'معتمد','Active':'فعال','Inactive':'غير فعال','Draft':'مسودة','Policy version':'إصدار السياسة','Retention days':'أيام الاحتفاظ','Collection purpose':'غرض جمع البيانات',
 'Extension UI preview':'معاينة واجهة الإضافة','Isolated test data. Chrome APIs require loading the unpacked extension.':'بيانات اختبار معزولة. يلزم تحميل الإضافة في Chrome لاستخدام واجهات المتصفح.',
 'A clear view of browser risk and the decisions that need attention.':'نظرة واضحة على مخاطر التصفح والقرارات التي تحتاج إلى اهتمام.','Check a web destination without sending query strings or fragments.':'افحص موقعاً دون إرسال معاملات الاستعلام أو أجزاء الرابط.','Review high-severity threats and document the response.':'راجع التهديدات عالية الخطورة ووثق الاستجابة.','Inspect confirmed signals and the evidence behind each score.':'راجع المؤشرات المؤكدة والأدلة التي تدعم كل درجة.','Understand the active policy and how confirmed signals affect severity.':'تعرف على السياسة الحالية وكيف تؤثر المؤشرات المؤكدة في مستوى الخطورة.','Calculate SHA-256 in the extension; send only the file hash for lookup.':'احسب SHA-256 داخل الإضافة وأرسل بصمة الملف فقط للفحص.','Follow past checks, assessment completeness and recorded decisions.':'راجع الفحوصات السابقة واكتمال التقييم والقرارات المسجلة.','Inspect devices associated with recorded scans.':'راجع الأجهزة المرتبطة بالفحوصات المسجلة.','Review the extension identities recorded by the backend.':'راجع هويات الإضافات المسجلة على الخادم.','Trace scans, threats, alert decisions and notification delivery.':'تابع الفحوصات والتهديدات وقرارات التنبيهات وتسليم الإشعارات.','Assign an investigation, record evidence and track it through resolution.':'حدد مسؤول التحقيق وسجل الأدلة وتابع الحادثة حتى حلها.','Manage controlled exceptions while preserving the original risk evidence.':'أدر الاستثناءات المعتمدة مع الاحتفاظ بأدلة الخطورة الأصلية.','Combine monthly statistics, machine-learning evidence and an AI-written report.':'اجمع الإحصاءات الشهرية وأدلة التعلم الآلي والتقرير المكتوب بالذكاء الاصطناعي.','Draft scoring changes, request independent review and activate approved policies.':'اقترح تغييرات التقييم واطلب مراجعة مستقلة ثم فعّل السياسات المعتمدة.','Define collection rules, access and retention for security evidence.':'حدد قواعد جمع الأدلة الأمنية وصلاحيات الوصول وفترة الاحتفاظ.','Compare scoring against labelled scenarios and examine incorrect outcomes.':'قارن التقييم بسيناريوهات مصنفة وراجع النتائج غير الصحيحة.','Record walkthroughs, accessibility issues and verified fixes.':'سجل اختبارات الاستخدام ومشكلات إمكانية الوصول والإصلاحات التي جرى التحقق منها.','Approve registrations and assign each account the minimum appropriate access.':'وافق على التسجيلات وحدد لكل حساب الحد الأدنى المناسب من الصلاحيات.','Understand findings and choose a sensible next action.':'افهم نتائج الفحص واختر الإجراء المناسب.','Review your assigned role and current verified session.':'راجع دورك المحدد وجلسة الدخول الحالية التي تم التحقق منها.','Review only the checks submitted through your own account.':'راجع الفحوصات التي أجريت من خلال حسابك فقط.','Request website access or review approvals before a blocked page can open.':'اطلب الوصول إلى المواقع أو راجع الطلبات قبل فتح صفحة محظورة.','Personalize the extension language and display times.':'خصص لغة الإضافة والمنطقة الزمنية لعرض الأوقات.',
};
export const translate=value=>preferences.language==='ar'?(AR[value]??value):value;
const originals=new WeakMap();
const originalAttributes=new WeakMap();
Object.assign(AR, {
 'Working…':'جارٍ تنفيذ الإجراء…','Wait for the current action to finish.':'انتظر حتى يكتمل الإجراء الحالي.','Your session ended. Sign in again with your password and authenticator.':'انتهت جلستك. سجّل الدخول مجدداً بكلمة المرور ورمز تطبيق المصادقة.',
 'New website visits are blocked before loading. Original destinations stay temporarily in browser memory; only explicit access requests reach the approval queue.':'تُحظر زيارات المواقع الجديدة قبل تحميلها. يبقى الرابط الأصلي مؤقتاً في ذاكرة المتصفح، وتُرسل طلبات الوصول الصريحة فقط إلى قائمة الموافقة.','New website visits require approval. A one-visit grant opens once; a whitelisted URL can be revisited until expiry or revocation. Reputation checks still run only when you choose them, and downloaded files are never read automatically.':'تحتاج زيارات المواقع الجديدة إلى موافقة. تُستخدم موافقة الزيارة الواحدة مرة واحدة، ويمكن إعادة زيارة الرابط المسموح حتى انتهاء الصلاحية أو الإلغاء. تُجرى فحوصات السمعة عند اختيارها فقط، ولا تُقرأ الملفات المحمّلة تلقائياً.','URL credentials are rejected. Only submitted destinations are reputation-checked. Approval requests keep the exact URL path, without query strings or fragments.':'تُرفض الروابط التي تحتوي على بيانات دخول. تُفحص سمعة المواقع التي ترسلها فقط. تحتفظ طلبات الموافقة بالمسار المحدد دون معاملات الاستعلام أو أجزاء الرابط.',
 'Check files and destinations; request website access; own history and guidance.':'فحص الملفات والمواقع وطلب الوصول، مع عرض السجل الشخصي والإرشادات.','Review monitoring and reports; manage alerts, cases and website approvals.':'مراجعة المراقبة والتقارير وإدارة التنبيهات والحوادث وطلبات المواقع.','Security operations, policies, exceptions, privacy, website approvals and report delivery.':'إدارة العمليات والسياسات والاستثناءات والخصوصية وطلبات المواقع وتسليم التقارير.',
 'Open the toolbar popup and review the current site.':'افتح نافذة الإضافة من شريط الأدوات وراجع الموقع الحالي.','Choose Check destination to submit a cleaned URL, or select a downloaded file for local hashing.':'اختر فحص الموقع لإرسال الرابط المنقح، أو حدد ملفاً محمّلاً لحساب بصمته محلياً.','Read the severity, assessment completeness and confirmed findings together.':'راجع مستوى الخطورة واكتمال التقييم والنتائج المؤكدة معاً.','Escalate High or Critical evidence to an administrator; keep Unknown outcomes visible.':'أبلغ المسؤول بالأدلة المرتفعة أو الحرجة، واحتفظ بالنتائج غير المعروفة ظاهرة.','Few confirmed signals in the checks performed. It does not guarantee safety.':'مؤشرات مؤكدة قليلة في الفحوصات التي أُجريت. لا تضمن هذه النتيجة الأمان.','Review findings and avoid unnecessary exposure.':'راجع النتائج وتجنب التعرض غير الضروري للمخاطر.','Avoid opening the destination or file; investigate evidence and affected devices.':'تجنب فتح الموقع أو الملف، وحقق في الأدلة والأجهزة المتأثرة.','The required information was unavailable. Retry later or use another approved investigation method.':'لم تتوفر المعلومات المطلوبة. أعد المحاولة لاحقاً أو استخدم طريقة تحقيق أخرى معتمدة.','Administrators can acknowledge threats, link evidence to a case and record a resolution. Exceptions affect notifications while retaining the original risk result. Scoring changes need an independent administrator’s approval.':'يمكن للمسؤولين مراجعة التهديدات وربط الأدلة بحادثة وتسجيل الحل. تؤثر الاستثناءات في الإشعارات مع الاحتفاظ بنتيجة الخطورة الأصلية. تحتاج تغييرات التقييم إلى موافقة مسؤول مستقل.','Monthly AI summaries are drafts that need review. Machine learning highlights unusual activity; it does not prove that malware is present.':'الملخصات الشهرية بالذكاء الاصطناعي مسودات تحتاج إلى مراجعة. يحدد التعلم الآلي النشاط غير المعتاد ولا يثبت وجود برمجيات ضارة.',
 'Skip to content':'الانتقال إلى المحتوى','Loading recorded evidence…':'جارٍ تحميل الأدلة المسجلة…','Working…':'جارٍ التنفيذ…','Chrome extension':'إضافة Chrome','Report periods':'فترات التقارير','UTC · Recorded scans':'UTC · الفحوصات المسجلة','Monitor · ExtSecure':'المراقبة · ExtSecure','Inventory · ExtSecure':'المخزون · ExtSecure','Investigate · ExtSecure':'التحقيق · ExtSecure','Govern · ExtSecure':'الإدارة · ExtSecure','Support · ExtSecure':'الدعم · ExtSecure',
 'Your browser · Your decision':'متصفحك · قرارك','A clearer security check.':'فحص أمني أكثر وضوحاً.','Current page':'الصفحة الحالية','Choose a web page':'اختر صفحة ويب','Check this destination before sharing information or downloading a file.':'افحص الموقع قبل مشاركة معلومات أو تنزيل ملف.','Site origin only · Approval blocking active':'عنوان الموقع فقط · حظر المواقع فعال','File check':'فحص ملف','Manager workspace':'لوحة المدير','Evidence at a glance.':'الأدلة في نظرة واحدة.','Review findings, manage incident cases and inspect weekly and monthly reports.':'راجع النتائج وأدر الحوادث الأمنية واطلع على التقارير الأسبوعية والشهرية.','Open security console':'فتح لوحة الأمان','Approved access · Backend scoring':'وصول معتمد · تقييم الخطورة على الخادم','Review alerts':'مراجعة التنبيهات','Lifetime recorded checks':'جميع الفحوصات المسجلة','Confirmed high-severity results':'نتائج مؤكدة عالية الخطورة','Open and acknowledged alerts':'تنبيهات مفتوحة أو تمت مراجعتها','Keep confirmed threats and incomplete checks in view. A low score reflects available evidence; it does not guarantee safety.':'تابع التهديدات المؤكدة والفحوصات غير المكتملة. تعكس الدرجة المنخفضة الأدلة المتاحة ولا تضمن الأمان.','There are no scans yet. Start with a page or downloaded file; its evidence will appear here.':'لا توجد فحوصات بعد. ابدأ بصفحة أو ملف محمّل لتظهر أدلته هنا.',
 'Confirmed findings':'النتائج المؤكدة','No confirmed findings':'لا توجد مؤشرات مؤكدة','The lookup was unavailable. This is not a safe result.':'لم تتوفر نتيجة الاستعلام. لا تعني هذه النتيجة أن الهدف آمن.','This assessment found no confirmed signals in the checks performed.':'لم يجد التقييم مؤشرات مؤكدة في الفحوصات التي أُجريت.','Risk is scored by the backend.':'يقيّم الخادم مستوى الخطورة.','An administrator exception applies. Original risk evidence remains recorded.':'يوجد استثناء معتمد من المسؤول. تبقى أدلة الخطورة الأصلية مسجلة.','File reputation check':'فحص سمعة الملف','Choose a downloaded file':'اختر ملفاً محمّلاً','Downloaded file':'الملف المحمّل','File contents stay here. Only SHA-256 goes to the backend.':'يبقى محتوى الملف على جهازك. تُرسل بصمة SHA-256 فقط إلى الخادم.','Maximum 32 MiB · Nothing is uploaded automatically':'الحد الأقصى 32 MiB · لا يتم رفع أي ملف تلقائياً','Or paste an existing file hash':'أو ألصق بصمة ملف موجودة','64 hexadecimal characters':'64 رمزاً بنظام العد الست عشري','The backend checks hash reputation with VirusTotal and records an explainable risk result.':'يتحقق الخادم من سمعة البصمة عبر VirusTotal ويسجل نتيجة خطورة مع أسبابها.','Before you open the file':'قبل فتح الملف','An unknown hash or unavailable lookup means Unknown. Never treat it as a clean file.':'تعني البصمة غير المعروفة أو الاستعلام غير المتاح أن النتيجة غير معروفة. لا تعتبر الملف سليماً.','Use a file you are authorized to check. Large files can be hashed separately and checked using their SHA-256 digest.':'استخدم ملفاً لديك صلاحية فحصه. يمكن حساب بصمة الملفات الكبيرة بأداة منفصلة ثم فحص SHA-256.','Review my history':'مراجعة سجلي','Web address':'عنوان الموقع','Check a web destination':'فحص موقع ويب','A private first step':'خطوة أولى تراعي الخصوصية','Include the page path in the lookup. Query strings and fragments are always removed.':'تضمين مسار الصفحة في الاستعلام. تُزال دائماً معاملات الاستعلام وأجزاء الرابط.','By default, only the site origin is checked. The cleaned address is sent through your backend to VirusTotal after you choose Check destination.':'يُفحص عنوان الموقع الأساسي افتراضياً. يُرسل الرابط المنقح عبر الخادم إلى VirusTotal بعد اختيار فحص الموقع.',
 'Risk':'الخطورة','Checked':'تاريخ الفحص','Inspect':'عرض الأدلة','Filter recorded results':'تصفية النتائج المسجلة','Filter results…':'تصفية النتائج…','Threat':'التهديد','Detected':'تاريخ الكشف','Review an alert':'مراجعة تنبيه','Alert':'التنبيه','New status':'الحالة الجديدة','Record alert decision':'تسجيل قرار التنبيه','Your role has view-only access.':'دورك يسمح بالعرض فقط.','Delivery outcomes are recorded under Security events. Changing status does not resend notifications.':'تُسجل نتائج تسليم الإشعارات ضمن الأحداث الأمنية. لا يؤدي تغيير الحالة إلى إعادة إرسال الإشعار.','Severity levels':'مستويات الخطورة','Minimum':'الحد الأدنى','Maximum':'الحد الأقصى','How the score works':'كيف يُحسب التقييم','Points per confirmed signal':'نقاط كل مؤشر مؤكد','Signal':'المؤشر','Points':'النقاط','Explanation':'الشرح','Unknown means that no check could be assessed. It is separate from Low risk.':'تعني النتيجة غير المعروفة تعذر تقييم الفحوصات. وهي مختلفة عن الخطورة المنخفضة.','Only confirmed signals contribute points. The backend caps the score at 100 and preserves missing checks in assessment completeness.':'تضيف المؤشرات المؤكدة فقط نقاطاً. يحدد الخادم الدرجة القصوى عند 100 ويبين الفحوصات المفقودة في اكتمال التقييم.','Review security policies':'مراجعة السياسات الأمنية',
 'Exceptions change notification handling. They do not lower a score or erase the original finding.':'تغير الاستثناءات طريقة معالجة الإشعارات. ولا تخفض الدرجة أو تمحو النتيجة الأصلية.','Add a controlled exception':'إضافة استثناء معتمد','Match type':'نوع المطابقة','Exact URL or domain':'الرابط أو النطاق المحدد','Expiry (UTC)':'انتهاء الصلاحية (UTC)','Save exception':'حفظ الاستثناء','Deactivate an exception':'تعطيل استثناء','Exception':'الاستثناء','Deactivate exception':'تعطيل الاستثناء','Deactivate this exception. Original risk evidence stays recorded.':'تعطيل هذا الاستثناء مع الاحتفاظ بأدلة الخطورة الأصلية.','Exception audit trail':'سجل تدقيق الاستثناءات','State':'الحالة','Monthly evidence':'الأدلة الشهرية','Choose a completed calendar month in UTC.':'اختر شهراً تقويمياً مكتملاً بحسب UTC.','Report month':'شهر التقرير','Monthly total':'الإجمالي الشهري','Recorded high-severity results':'نتائج عالية الخطورة مسجلة','Unassessable checks':'فحوصات تعذر تقييمها','Monthly alert records':'التنبيهات الشهرية المسجلة','Machine-learning review':'مراجعة التعلم الآلي','Run monthly ML analysis':'تحليل الشهر بالتعلم الآلي','Run an activity review':'إجراء تحليل النشاط','At least 30 active historical days and three distinct observations are needed.':'يلزم توفر 30 يوماً سابقاً نشطاً وثلاث ملاحظات مختلفة على الأقل.','Learns from 90 days before the selected month. Unusual activity supports investigation; it does not establish a threat or change scan risk.':'يتعلم النموذج من الأيام التسعين السابقة للشهر المحدد. يساعد النشاط غير المعتاد في التحقيق ولا يثبت وجود تهديد أو يغير خطورة الفحص.','AI-written monthly summary':'الملخص الشهري بالذكاء الاصطناعي','The backend combines aggregate statistics with the ML evidence. Review the saved draft before delivering it to administrators.':'يجمع الخادم الإحصاءات وأدلة التعلم الآلي. راجع المسودة المحفوظة قبل إرسالها للمسؤولين.','Managers can review saved reports and ML results. Administrators prepare and deliver reports.':'يمكن للمديرين مراجعة التقارير المحفوظة ونتائج التعلم الآلي. يتولى المسؤولون إعداد التقارير وإرسالها.','Generate LLM draft':'إنشاء مسودة بالنموذج اللغوي','Send reviewed report':'إرسال التقرير بعد المراجعة','Saved report body · Read only':'نص التقرير المحفوظ · للقراءة فقط','Saved report history':'سجل التقارير المحفوظة','Month':'الشهر','Generated':'تاريخ الإنشاء','Sent':'تاريخ الإرسال','Channel':'القناة',
 'Pending registrations':'طلبات التسجيل المعلقة','Registration':'طلب التسجيل','Assign role':'تحديد الدور','Record access decision':'تسجيل قرار الوصول','Approved accounts':'الحسابات المعتمدة','Source':'المصدر','Change account access':'تغيير صلاحيات الحساب','Account':'الحساب','Apply access change':'تطبيق تغيير الصلاحيات','Privilege guide':'دليل الصلاحيات','Access':'الوصول','Only the Head of Administrator approves access or changes account privileges. Every role completes password and authenticator sign-in.':'يعتمد رئيس المسؤولين وحده الحسابات ويغير صلاحياتها. تتطلب جميع الأدوار كلمة مرور ورمز تطبيق المصادقة.','Check files and destinations; own history and guidance.':'فحص الملفات والمواقع وطلب الوصول، مع عرض السجل الشخصي والإرشادات.','Review monitoring and reports; manage alerts and cases.':'مراجعة المراقبة والتقارير وإدارة التنبيهات والحوادث وطلبات المواقع.','Security operations, policies, exceptions, privacy and report delivery.':'إدارة العمليات والسياسات والاستثناءات والخصوصية وطلبات المواقع وتسليم التقارير.','All workflows plus registration approval and account access control.':'جميع المهام، إضافة إلى اعتماد التسجيلات وإدارة صلاحيات الحسابات.',
 'Case':'الحادثة','Assigned to':'المسؤول','Source scan':'الفحص المرتبط','Case title':'عنوان الحادثة','Assign to':'تعيين المسؤول','Open an investigation':'فتح تحقيق','Open incident case':'فتح حادثة أمنية','Investigation workspace':'لوحة التحقيق','Inspect source evidence':'عرض الأدلة الأصلية','No notes yet':'لا توجد ملاحظات بعد','Record evidence references without private URLs, passwords or personal details.':'سجل مراجع الأدلة دون روابط خاصة أو كلمات مرور أو تفاصيل شخصية.','Add an investigation note':'إضافة ملاحظة تحقيق','Note':'الملاحظة','Update case or record resolution':'تحديث الحادثة أو تسجيل الحل','Assigned investigator':'المحقق المسؤول','Update investigation':'تحديث التحقيق','Linked scan evidence is held during investigation. Resolving a case preserves its score and history.':'يُحتفظ بأدلة الفحص المرتبطة طوال التحقيق. يبقى التقييم والسجل محفوظين بعد حل الحادثة.',
 'Active scoring policy':'سياسة التقييم الحالية','Draft a scoring change':'اقتراح تغيير التقييم','Save policy draft':'حفظ مسودة السياسة','Policy revisions':'مراجعات السياسات','Author':'الكاتب','Reviewer':'المراجع','Revision':'المراجعة','Starts at':'يبدأ عند','Ends at':'ينتهي عند','Proposed points':'النقاط المقترحة','Proposed minimum':'الحد الأدنى المقترح','Submit independent review':'إرسال مراجعة مستقلة','Activate approved policy':'تفعيل السياسة المعتمدة','Drafts do not affect live scores. A different approved administrator must review a draft before activation.':'لا تؤثر المسودات في التقييمات الحالية. يجب أن يراجع مسؤول معتمد آخر المسودة قبل تفعيلها.','You created this draft. Another administrator must review it.':'أنت أنشأت هذه المسودة. يجب أن يراجعها مسؤول آخر.','Data collection and access':'جمع البيانات والوصول إليها','Data':'البيانات','Stored':'البيانات المحفوظة','Purpose':'الغرض','Scan retention period (days)':'مدة الاحتفاظ بالفحوصات بالأيام','Save privacy rules':'حفظ قواعد الخصوصية','Retention preview':'معاينة الاحتفاظ بالبيانات','Eligible scans':'الفحوصات المؤهلة للحذف','Held for cases':'محفوظة للحوادث','Configured period':'المدة المحددة','Investigation evidence is preserved':'تُحفظ أدلة التحقيق','No scan records are currently eligible for deletion.':'لا توجد سجلات فحص مؤهلة للحذف حالياً.',
 'Run a labelled scoring evaluation':'تقييم سيناريوهات مصنفة','Dataset version':'إصدار مجموعة البيانات','Labelled scenarios (JSON)':'السيناريوهات المصنفة (JSON)','Compare policy with baseline':'مقارنة السياسة بخط الأساس','Dataset':'مجموعة البيانات','Policy':'السياسة','Run time':'وقت التشغيل','Evaluation results':'نتائج التقييم','Run':'التشغيل','Active policy':'السياسة الحالية','Baseline policy':'سياسة خط الأساس','True positives':'كشف صحيح للتهديدات','False positives':'إنذارات خاطئة','Missed threats':'تهديدات لم تُكتشف','Scenario':'السيناريو','Expected':'المتوقع','Result':'النتيجة','Prediction':'التنبؤ','Download evaluation evidence':'تنزيل أدلة التقييم','Record a usability or accessibility check':'تسجيل اختبار استخدام أو إمكانية وصول','Task tested':'المهمة المختبرة','Category':'الفئة','Keyboard navigation':'التنقل بلوحة المفاتيح','Colour contrast':'تباين الألوان','Screen reader':'قارئ الشاشة','Understanding risk':'فهم الخطورة','Task workflow':'تنفيذ المهمة','Observed outcome':'النتيجة الملحوظة','Observation':'الملاحظة','Record test':'تسجيل الاختبار','Task':'المهمة','Outcome':'النتيجة','Record a fix or verified retest':'تسجيل إصلاح أو إعادة اختبار مؤكدة','Test record':'سجل الاختبار','Issue status':'حالة المشكلة','Fix or retest evidence':'أدلة الإصلاح أو إعادة الاختبار','Update record':'تحديث السجل','Record actual walkthroughs and observations. A code check alone does not establish accessibility conformance.':'سجل اختبارات الاستخدام الفعلية والملاحظات. لا يثبت فحص الشفرة وحده الالتزام بمعايير إمكانية الوصول.',
 'A useful first workflow':'خطوات أولى مفيدة','Understand the result':'فهم النتيجة','Keep decisions accountable':'توثيق القرارات','Review my account':'مراجعة حسابي','Check a file':'فحص ملف','Your approved access':'صلاحياتك المعتمدة','Detail':'التفصيل','Value':'القيمة','Sign out on this browser':'تسجيل الخروج من هذا المتصفح','Password and authenticator verification completed for this session.':'اكتمل التحقق بكلمة المرور وتطبيق المصادقة لهذه الجلسة.','Your role is assigned by the Head of Administrator. Contact that account owner when your responsibilities change.':'يحدد رئيس المسؤولين دورك. تواصل معه عند تغير مسؤولياتك.','Sessions are stored in Chrome’s memory-only extension storage. Passwords and authenticator secrets are not saved by the extension.':'تُحفظ الجلسات في ذاكرة الإضافة داخل Chrome فقط. لا تحفظ الإضافة كلمات المرور أو أسرار المصادقة.','Record the evidence and why this action is appropriate.':'سجل الأدلة وسبب ملاءمة هذا الإجراء.',
});
Object.assign(AR,{
 'AI risk explanation':'شرح المخاطر بالذكاء الاصطناعي',
 'The model explains recorded evidence and suggests actions. It does not decide risk or prove a file is safe.':'يفسّر النموذج الأدلة المسجلة ويقترح إجراءات. لا يحدد مستوى الخطورة ولا يثبت أمان الملف.',
 'Optionally share bounded page or text-file content with the backend and configured AI provider.':'مشاركة محتوى محدود من الصفحة أو الملف النصي اختياريًا مع الخادم ومزود الذكاء الاصطناعي المهيأ.',
 'Exact scanned public HTTPS URL (optional)':'رابط HTTPS العام المطابق للفحص (اختياري)',
 'Matching UTF-8 text file (optional, maximum 256 KiB)':'ملف UTF-8 نصي مطابق للبصمة (اختياري، بحد أقصى 256 كيلوبايت)',
 'Without optional content, only stored reputation evidence is explained. Binary files use hash evidence. No content is executed. Query strings and fragments are excluded.':'دون المحتوى الاختياري، يُشرح دليل السمعة المسجل فقط. تعتمد الملفات الثنائية على دليل البصمة. لا يُشغّل أي محتوى، وتُستبعد معلمات الرابط وأجزاؤه.',
 'Explain evidence and recommendations':'شرح الأدلة والتوصيات',
 'AI-assisted draft · Review against the original evidence. Original severity is unchanged.':'مسودة بمساعدة الذكاء الاصطناعي · راجعها مع الأدلة الأصلية. مستوى الخطورة الأصلي لم يتغير.',
 'Recommended actions':'الإجراءات الموصى بها',
 'Weekly and monthly AI reports':'تقارير الذكاء الاصطناعي الأسبوعية والشهرية',
 'Completed UTC periods only. Weekly periods begin on Monday. Each saved snapshot includes every alert and AI explanation recorded during that period, plus an aggregate narrative. The downloadable archive contains all rows; identifiers and raw content are excluded from the model prompt.':'فترات مكتملة بتوقيت UTC فقط، وتبدأ الأسابيع يوم الاثنين. يشمل كل تقرير محفوظ جميع التنبيهات والشروح المسجلة خلال الفترة، إضافة إلى ملخص إجمالي. يتضمن الأرشيف القابل للتنزيل جميع السجلات؛ وتُستبعد المعرفات والمحتويات الخام من مدخلات النموذج.',
 'Report frequency':'تكرار التقرير','Weekly':'أسبوعي','Monthly':'شهري','Period start':'بداية الفترة',
 'Generate period report':'إنشاء تقرير الفترة','Saved AI report snapshots':'تقارير الذكاء الاصطناعي المحفوظة',
 'Download complete report archive':'تنزيل أرشيف التقرير كاملًا','No saved AI period reports.':'لا توجد تقارير فترات محفوظة.',
 'Administrators generate reports. Managers can review saved reports.':'ينشئ المسؤولون التقارير. يمكن للمديرين مراجعة التقارير المحفوظة.',
 'AI-assisted draft · Review before sharing with administrators.':'مسودة بمساعدة الذكاء الاصطناعي · راجعها قبل مشاركتها مع المسؤولين.',
});
export function localize(root=document.body){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  while(walker.nextNode()){
    const node=walker.currentNode;
    if(node.parentElement?.closest('script,style,pre,code,textarea,.code,[data-no-translate]'))continue;
    const previous=originals.get(node);
    const original=previous&&node.nodeValue===previous.rendered?previous.source:node.nodeValue,trimmed=original.trim().replace(/^·\s*/, '');
    if(!AR[trimmed])continue;
    const replacement=original.replace(trimmed,translate(trimmed));
    originals.set(node,{source:original,rendered:replacement});
    if(node.nodeValue!==replacement)node.nodeValue=replacement;
  }
  root.querySelectorAll('[aria-label],[placeholder]').forEach(element=>{
    if(element.closest('script,style,pre,code,.code,[data-no-translate]'))return;
    const attributes=originalAttributes.get(element)??{};
    for(const name of ['aria-label','placeholder']){
      const value=element.getAttribute(name),previous=attributes[name];
      const source=previous&&value===previous.rendered?previous.source:value;
      if(!AR[source]){delete attributes[name];continue;}
      const rendered=translate(source);
      attributes[name]={source,rendered};
      if(value!==rendered)element.setAttribute(name,rendered);
    }
    originalAttributes.set(element,attributes);
  });
}
export function observeLocalization(root=document.body){localize(root);const observer=new MutationObserver(()=>localize(root));observer.observe(root,{childList:true,subtree:true,characterData:true});return observer;}
