export const LANGUAGES=[['en','English'],['ar','العربية']];
export const TIME_ZONES=[['UTC','UTC'],['Asia/Riyadh','Saudi Arabia / KSA · UTC+3'],['Asia/Dubai','United Arab Emirates · UTC+4'],['Asia/Bahrain','Bahrain · UTC+3'],['Europe/London','United Kingdom'],['Europe/Paris','Central Europe'],['America/New_York','New York'],['Asia/Kolkata','India'],['Asia/Tokyo','Japan']];
export const DEFAULT_PREFERENCES={language:'en',timeZone:'UTC'};
export function normalizePreferences(value={},strict=false){
  const language=value?.language??'en',timeZone=value?.timeZone??'UTC';
  const validLanguage=LANGUAGES.some(([v])=>v===language),validZone=TIME_ZONES.some(([v])=>v===timeZone);
  if(strict&&(!validLanguage||!validZone))throw new Error('Choose a supported language and time zone.');
  return {language:validLanguage?language:'en',timeZone:validZone?timeZone:'UTC'};
}
let preferences={...DEFAULT_PREFERENCES};
export function setPreferences(value){preferences=normalizePreferences(value);if(typeof document!=='undefined'){document.documentElement.lang=preferences.language;document.documentElement.dir=preferences.language==='ar'?'rtl':'ltr';}return preferences;}
export const getPreferences=()=>({...preferences});
export function formatDate(value){if(!value)return '—';const date=new Date(value);if(!Number.isFinite(date.getTime()))return '—';return new Intl.DateTimeFormat(preferences.language==='ar'?'ar-SA-u-ca-gregory':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:preferences.timeZone}).format(date)+' · '+preferences.timeZone;}
export const formatNumber=value=>Number.isFinite(value)?new Intl.NumberFormat(preferences.language).format(value):'—';
const AR={
 'Browser security':'أمان التصفح','Overview':'نظرة عامة','Scan a page':'فحص صفحة','Alerts':'التنبيهات','Findings':'نتائج الفحص','Risk levels':'مستويات الخطورة','Downloaded-file checks':'فحص الملفات المحمّلة','File checks':'فحص الملفات','Scan history':'سجل الفحص','Devices':'الأجهزة','Extensions':'الإضافات','Security events':'الأحداث الأمنية','Incident cases':'الحوادث الأمنية','Whitelist & overrides':'الاستثناءات الأمنية','Monthly reports':'التقارير الشهرية','Security policies':'السياسات الأمنية','Privacy governance':'حوكمة الخصوصية','Detection evaluation':'تقييم جودة الكشف','Usability and accessibility':'سهولة الاستخدام وإمكانية الوصول','Usability & accessibility':'سهولة الاستخدام وإمكانية الوصول','Accounts':'الحسابات','Security guidance':'الإرشادات الأمنية','My account':'حسابي','My file history':'سجل فحوصاتي','Website access':'صلاحيات المواقع','Settings':'الإعدادات',
 'Monitor':'المراقبة','Inventory':'المخزون','Investigate':'التحقيق','Govern':'الإدارة','Support':'الدعم','Extension console':'لوحة الإضافة','Extension navigation':'التنقل في الإضافة','Sign out':'تسجيل الخروج','Refresh':'تحديث','2FA verified':'تم التحقق بخطوتين','Head of Administrator':'رئيس المسؤولين','Administrator':'مسؤول النظام','Manager':'مدير','Normal user':'مستخدم عادي',
 'Low':'منخفض','Medium':'متوسط','High':'مرتفع','Critical':'حرج','Unknown':'غير معروف','pending':'قيد الانتظار','approved':'موافق عليه','rejected':'مرفوض','consumed':'تم استخدامه','open':'مفتوح','acknowledged':'تمت المراجعة','resolved':'تم الحل','investigating':'قيد التحقيق','once':'زيارة واحدة','whitelist':'القائمة المسموحة',
 'Welcome to ExtSecure':'مرحباً بك في ExtSecure','Create your account':'إنشاء حساب','Log in':'تسجيل الدخول','Register account':'إنشاء حساب جديد','Username':'اسم المستخدم','Password':'كلمة المرور','Confirm password':'تأكيد كلمة المرور','Continue securely':'متابعة آمنة','Verify it’s you':'التحقق من هويتك','Six-digit authenticator code':'رمز تطبيق المصادقة المكوّن من ستة أرقام','Verify and sign in':'تحقق وسجّل الدخول','Start sign-in again':'بدء تسجيل الدخول مجدداً','Your credentials':'بيانات الدخول','Account details':'بيانات الحساب','Set up authenticator':'إعداد تطبيق المصادقة','Set up your authenticator':'إعداد تطبيق المصادقة','Authenticator enrollment':'ربط تطبيق المصادقة','Verify account':'التحقق من الحساب','Cancel registration':'إلغاء التسجيل','Enter the setup key manually':'إدخال مفتاح الإعداد يدوياً','Password accepted · Authenticator required':'تم قبول كلمة المرور · يلزم رمز المصادقة','No invitation code required.':'لا يلزم رمز دعوة.',
 'Sign in to your approved account to review browser security.':'سجّل الدخول إلى حسابك المعتمد لمراجعة أمان التصفح.','Use the current code from your authenticator app to complete sign-in.':'أدخل الرمز الحالي من تطبيق المصادقة لإكمال تسجيل الدخول.','The backend verifies both steps before granting access.':'يتحقق الخادم من الخطوتين قبل منح الوصول.','Scan the QR code in your authenticator app, then verify a six-digit code.':'امسح رمز QR في تطبيق المصادقة، ثم أدخل رمز التحقق المكوّن من ستة أرقام.','Set up an account and authenticator, then request administrator approval.':'أنشئ حساباً واربط تطبيق المصادقة، ثم اطلب موافقة المسؤول.','New accounts need approval. Every role uses password and authenticator verification.':'تحتاج الحسابات الجديدة إلى موافقة. تتطلب جميع الأدوار كلمة مرور ورمز مصادقة.','Setup expires after 15 minutes. Access requires approval by the Head of Administrator.':'تنتهي صلاحية الإعداد بعد 15 دقيقة. يلزم الحصول على موافقة رئيس المسؤولين للوصول.','Choose at least 12 characters. The main administrator assigns your role after approval.':'اختر كلمة مرور من 12 حرفاً على الأقل. يحدد المسؤول الرئيسي دورك بعد الموافقة.',
 'A calmer view of browser security':'رؤية أوضح لأمان التصفح','Clear signals.':'مؤشرات واضحة.','Confident decisions.':'قرارات مدروسة.','Check destinations, investigate threats and keep the evidence together in your browser.':'افحص المواقع، وحقق في التهديدات، واحتفظ بالأدلة في لوحة المتصفح.','Approved accounts. Two required sign-in steps.':'حسابات معتمدة وخطوتان إلزاميتان لتسجيل الدخول.','Local file hashing. Backend-owned risk scores.':'حساب بصمة الملف محلياً وتقييم الخطورة على الخادم.',
 'Language and time zone':'اللغة والمنطقة الزمنية','Language':'اللغة','Time zone':'المنطقة الزمنية','Save preferences':'حفظ التفضيلات','Preferences saved.':'تم حفظ التفضيلات.','Choose a supported language and time zone.':'اختر لغة ومنطقة زمنية مدعومتين.','Arabic and English are supported. Times follow your selected zone; monthly report boundaries stay in UTC.':'تتوفر العربية والإنجليزية. تُعرض الأوقات وفق المنطقة المحددة، وتبقى حدود التقارير الشهرية حسب UTC.','These settings apply to the popup, console and blocked-page screen.':'تُطبق هذه الإعدادات على النافذة المنبثقة ولوحة الإضافة وصفحة حظر المواقع.','Recorded evidence and administrator notes keep their original language.':'تُعرض الأدلة المسجلة وملاحظات المسؤولين بلغتها الأصلية.','Saudi Arabia / KSA · UTC+3':'السعودية · UTC+3','United Arab Emirates · UTC+4':'الإمارات العربية المتحدة · UTC+4','Bahrain · UTC+3':'البحرين · UTC+3','United Kingdom':'المملكة المتحدة','Central Europe':'وسط أوروبا','New York':'نيويورك','India':'الهند','Japan':'اليابان',
 'Website approval required':'يلزم اعتماد الموقع','This website is blocked':'هذا الموقع محظور','Request access':'طلب الوصول','Open approved website':'فتح الموقع المعتمد','Check approval':'التحقق من الموافقة','Open approval queue':'فتح قائمة الطلبات','Sign in to request access':'سجّل الدخول لطلب الوصول','Destination':'الموقع المطلوب','Request reason':'سبب الطلب','Review request':'مراجعة الطلب','Approve one visit':'الموافقة على زيارة واحدة','Approve URL whitelist':'إضافة الرابط للقائمة المسموحة','Reject request':'رفض الطلب','Decision':'القرار','Decision reason':'سبب القرار','Whitelist duration (days)':'مدة السماح بالأيام','Submit decision':'حفظ القرار','Revoke whitelist entry':'إلغاء السماح بالرابط','Revoke access':'إلغاء السماح','Approved URL whitelist':'روابط المواقع المسموحة','Access requests':'طلبات الوصول','Requester':'مقدم الطلب','Requested':'تاريخ الطلب','Reviewed by':'راجعه','Expires':'تنتهي الصلاحية','Status':'الحالة','Reason':'السبب','URL':'الرابط','Select request':'اختر الطلب','Select whitelist entry':'اختر الرابط المسموح','No pending requests':'لا توجد طلبات قيد الانتظار','Visit approval is ready.':'تمت الموافقة على الزيارة.','Waiting for manager or administrator approval.':'بانتظار موافقة مدير أو مسؤول النظام.','The website stays blocked until an approved visit is opened.':'يبقى الموقع محظوراً حتى فتح زيارة معتمدة.','A one-visit approval expires after 10 minutes and is used once. A whitelist approval is reusable by approved accounts until expiry or revocation.':'تنتهي موافقة الزيارة الواحدة بعد 10 دقائق وتُستخدم مرة واحدة. يمكن للحسابات المعتمدة استخدام الرابط المسموح حتى انتهاء الصلاحية أو إلغاء الموافقة.','The exact scheme, host, port and path are approved. Query strings and fragments are not stored in approval requests.':'تشمل الموافقة البروتوكول والمضيف والمنفذ والمسار المحدد. لا تُحفظ معاملات الاستعلام أو أجزاء الرابط في الطلبات.','Another manager or administrator must review your own request':'يجب أن يراجع مدير أو مسؤول آخر طلبك.','Access request sent. The website remains blocked until approval.':'تم إرسال الطلب. يبقى الموقع محظوراً إلى حين الموافقة.','Confirm you have reviewed the destination and the business need.':'أؤكد مراجعة الموقع المطلوب وسبب الحاجة إليه.','Add the URL and explain why access is needed.':'أدخل الرابط واشرح سبب حاجتك إلى الوصول.','Requests and whitelist decisions are recorded for audit.':'تُسجل طلبات الوصول وقرارات السماح لأغراض التدقيق.','Managing website approval does not change risk scores or suppress threat alerts.':'لا تغير الموافقة على المواقع درجات الخطورة ولا توقف تنبيهات التهديدات.','Sign in':'تسجيل الدخول','Return to safety':'العودة إلى صفحة آمنة','Close this tab':'إغلاق هذه الصفحة',
 'Save change':'حفظ التغيير','No records yet':'لا توجد سجلات بعد','Nothing to review':'لا توجد نتائج للمراجعة','No records are available for this selection.':'لا توجد سجلات لهذا الاختيار.','Recorded results':'النتائج المسجلة','Loading your workspace…':'جارٍ تحميل اللوحة…','Try again':'حاول مجدداً','View all':'عرض الكل','Check a page':'فحص صفحة','Check a downloaded file':'فحص ملف محمّل','Check current destination':'فحص الموقع الحالي','Open console':'فتح لوحة الإضافة','Security posture':'الحالة الأمنية','Risk distribution':'توزيع الخطورة','Activity over 14 days':'النشاط خلال 14 يوماً','Recent security events':'الأحداث الأمنية الأخيرة','All time':'كل الفترات','All scans':'جميع الفحوصات','High / Critical':'مرتفع / حرج','Total scans':'إجمالي الفحوصات','Awaiting review':'بانتظار المراجعة','Devices seen':'الأجهزة المسجلة','Keep the next action clear':'حدد الخطوة التالية بوضوح','Check a download':'فحص ملف محمّل','Investigate with evidence':'التحقيق بالاستناد إلى الأدلة','Read security guidance':'قراءة الإرشادات الأمنية','Your workspace is ready.':'اللوحة جاهزة.','Review the signals that need you.':'راجع المؤشرات التي تحتاج إلى اهتمامك.','Hash the file in your browser. File contents stay on this device.':'احسب بصمة الملف داخل المتصفح. يبقى محتوى الملف على هذا الجهاز.','Link a finding to a case and record the decision that follows.':'اربط نتيجة الفحص بحادثة وسجل القرار المتخذ.','No recent activity':'لا يوجد نشاط حديث','New scans and security decisions will appear here.':'ستظهر هنا الفحوصات الجديدة والقرارات الأمنية.','Completed checks will appear here with their evidence and next steps.':'ستظهر الفحوصات المكتملة مع الأدلة والخطوات التالية.',
 'Score':'الدرجة','Severity':'مستوى الخطورة','Assessment':'التقييم','Time':'الوقت','Target':'الهدف','ID':'المعرّف','Evidence':'الأدلة','Next action':'الخطوة التالية','Filter records':'تصفية السجلات','Search records':'البحث في السجلات','Review':'مراجعة','Created':'تاريخ الإنشاء','Name':'الاسم','Role':'الدور','Version':'الإصدار','Last seen':'آخر ظهور','Type':'النوع','Message':'الرسالة','Actor':'المنفذ','Action':'الإجراء','Details':'التفاصيل','Back to results':'العودة إلى النتائج','Current session':'الجلسة الحالية','Session expires':'انتهاء الجلسة','Role and access':'الدور والصلاحيات','Assigned role':'الدور المحدد','Signed in as':'الحساب الحالي','Your account':'حسابك','Available workspaces':'الأقسام المتاحة','File name':'اسم الملف','File hash':'بصمة الملف','Choose a file':'اختيار ملف','SHA-256 hash':'بصمة SHA-256','Check file hash':'فحص بصمة الملف','Scan URL':'فحص الرابط','Check destination':'فحص الموقع','Include URL path':'تضمين مسار الرابط','Local hashing':'حساب البصمة محلياً','Risk result':'نتيجة الخطورة','No result yet':'لا توجد نتيجة بعد','Select a completed month':'اختر شهراً مكتملاً','Month (UTC)':'الشهر (UTC)','Monthly statistics':'الإحصاءات الشهرية','Machine learning':'التعلم الآلي','Run activity review':'تحليل النشاط','Generate AI draft':'إنشاء مسودة بالذكاء الاصطناعي','Send to administrators':'الإرسال إلى المسؤولين','Download ML evidence':'تنزيل أدلة التعلم الآلي','Unusual':'غير معتاد','Day':'اليوم','Scans':'الفحوصات','AI-written summary':'ملخص بالذكاء الاصطناعي','Report delivery':'تسليم التقرير','Create case':'إنشاء حادثة','Title':'العنوان','Assignee':'المسؤول عن الحادثة','Investigation notes':'ملاحظات التحقيق','Add note':'إضافة ملاحظة','Update case':'تحديث الحادثة','Resolution':'الحل','Review alert':'مراجعة التنبيه','Update status':'تحديث الحالة','Approved':'معتمد','Active':'فعال','Inactive':'غير فعال','Draft':'مسودة','Policy version':'إصدار السياسة','Retention days':'أيام الاحتفاظ','Collection purpose':'غرض جمع البيانات',
 'Extension UI preview':'معاينة واجهة الإضافة','Isolated test data. Chrome APIs require loading the unpacked extension.':'بيانات اختبار معزولة. يلزم تحميل الإضافة في Chrome لاستخدام واجهات المتصفح.',
 'A clear view of browser risk and the decisions that need attention.':'نظرة واضحة على مخاطر التصفح والقرارات التي تحتاج إلى اهتمام.','Check a web destination without sending query strings or fragments.':'افحص موقعاً دون إرسال معاملات الاستعلام أو أجزاء الرابط.','Review high-severity threats and document the response.':'راجع التهديدات عالية الخطورة ووثق الاستجابة.','Inspect confirmed signals and the evidence behind each score.':'راجع المؤشرات المؤكدة والأدلة التي تدعم كل درجة.','Understand the active policy and how confirmed signals affect severity.':'تعرف على السياسة الحالية وكيف تؤثر المؤشرات المؤكدة في مستوى الخطورة.','Calculate SHA-256 in the extension; send only the file hash for lookup.':'احسب SHA-256 داخل الإضافة وأرسل بصمة الملف فقط للفحص.','Follow past checks, assessment completeness and recorded decisions.':'راجع الفحوصات السابقة واكتمال التقييم والقرارات المسجلة.','Inspect devices associated with recorded scans.':'راجع الأجهزة المرتبطة بالفحوصات المسجلة.','Review the extension identities recorded by the backend.':'راجع هويات الإضافات المسجلة على الخادم.','Trace scans, threats, alert decisions and notification delivery.':'تابع الفحوصات والتهديدات وقرارات التنبيهات وتسليم الإشعارات.','Assign an investigation, record evidence and track it through resolution.':'حدد مسؤول التحقيق وسجل الأدلة وتابع الحادثة حتى حلها.','Manage controlled exceptions while preserving the original risk evidence.':'أدر الاستثناءات المعتمدة مع الاحتفاظ بأدلة الخطورة الأصلية.','Combine monthly statistics, machine-learning evidence and an AI-written report.':'اجمع الإحصاءات الشهرية وأدلة التعلم الآلي والتقرير المكتوب بالذكاء الاصطناعي.','Draft scoring changes, request independent review and activate approved policies.':'اقترح تغييرات التقييم واطلب مراجعة مستقلة ثم فعّل السياسات المعتمدة.','Define collection rules, access and retention for security evidence.':'حدد قواعد جمع الأدلة الأمنية وصلاحيات الوصول وفترة الاحتفاظ.','Compare scoring against labelled scenarios and examine incorrect outcomes.':'قارن التقييم بسيناريوهات مصنفة وراجع النتائج غير الصحيحة.','Record walkthroughs, accessibility issues and verified fixes.':'سجل اختبارات الاستخدام ومشكلات إمكانية الوصول والإصلاحات التي جرى التحقق منها.','Approve registrations and assign each account the minimum appropriate access.':'وافق على التسجيلات وحدد لكل حساب الحد الأدنى المناسب من الصلاحيات.','Understand findings and choose a sensible next action.':'افهم نتائج الفحص واختر الإجراء المناسب.','Review your assigned role and current verified session.':'راجع دورك المحدد وجلسة الدخول الحالية التي تم التحقق منها.','Review only the checks submitted through your own account.':'راجع الفحوصات التي أجريت من خلال حسابك فقط.','Request website access or review approvals before a blocked page can open.':'اطلب الوصول إلى المواقع أو راجع الطلبات قبل فتح صفحة محظورة.','Personalize the extension language and display times.':'خصص لغة الإضافة والمنطقة الزمنية لعرض الأوقات.',
};
export const translate=value=>preferences.language==='ar'?(AR[value]??value):value;
const originals=new WeakMap();
const originalAttributes=new WeakMap();
Object.assign(AR, {
 'Working…':'جارٍ تنفيذ الإجراء…','Wait for the current action to finish.':'انتظر حتى يكتمل الإجراء الحالي.','Your session ended. Sign in again with your password and authenticator.':'انتهت جلستك. سجّل الدخول مجدداً بكلمة المرور ورمز تطبيق المصادقة.',
 'New website visits are blocked before loading. Original destinations stay temporarily in browser memory; only explicit access requests reach the approval queue.':'تُحظر زيارات المواقع الجديدة قبل تحميلها. يبقى الرابط الأصلي مؤقتاً في ذاكرة المتصفح، وتُرسل طلبات الوصول الصريحة فقط إلى قائمة الموافقة.','New website visits require approval. A one-visit grant opens once; a whitelisted URL can be revisited until expiry or revocation. Reputation checks still run only when you choose them, and downloaded files are never read automatically.':'تحتاج زيارات المواقع الجديدة إلى موافقة. تُستخدم موافقة الزيارة الواحدة مرة واحدة، ويمكن إعادة زيارة الرابط المسموح حتى انتهاء الصلاحية أو الإلغاء. تُجرى فحوصات السمعة عند اختيارها فقط، ولا تُقرأ الملفات المحمّلة تلقائياً.','URL credentials are rejected. Only submitted destinations are reputation-checked. Approval requests keep the exact URL path, without query strings or fragments.':'تُرفض الروابط التي تحتوي على بيانات دخول. تُفحص سمعة المواقع التي ترسلها فقط. تحتفظ طلبات الموافقة بالمسار المحدد دون معاملات الاستعلام أو أجزاء الرابط.',
 'Check files and destinations; request website access; own history and guidance.':'فحص الملفات والمواقع وطلب الوصول، مع عرض السجل الشخصي والإرشادات.','Review monitoring and reports; manage alerts, cases and website approvals.':'مراجعة المراقبة والتقارير وإدارة التنبيهات والحوادث وطلبات المواقع.','Security operations, policies, exceptions, privacy, website approvals and report delivery.':'إدارة العمليات والسياسات والاستثناءات والخصوصية وطلبات المواقع وتسليم التقارير.',
 'Open the toolbar popup and review the current site.':'افتح نافذة الإضافة من شريط الأدوات وراجع الموقع الحالي.','Choose Check destination to submit a cleaned URL, or select a downloaded file for local hashing.':'اختر فحص الموقع لإرسال الرابط المنقح، أو حدد ملفاً محمّلاً لحساب بصمته محلياً.','Read the severity, assessment completeness and confirmed findings together.':'راجع مستوى الخطورة واكتمال التقييم والنتائج المؤكدة معاً.','Escalate High or Critical evidence to an administrator; keep Unknown outcomes visible.':'أبلغ المسؤول بالأدلة المرتفعة أو الحرجة، واحتفظ بالنتائج غير المعروفة ظاهرة.','Few confirmed signals in the checks performed. It does not guarantee safety.':'مؤشرات مؤكدة قليلة في الفحوصات التي أُجريت. لا تضمن هذه النتيجة الأمان.','Review findings and avoid unnecessary exposure.':'راجع النتائج وتجنب التعرض غير الضروري للمخاطر.','Avoid opening the destination or file; investigate evidence and affected devices.':'تجنب فتح الموقع أو الملف، وحقق في الأدلة والأجهزة المتأثرة.','The required information was unavailable. Retry later or use another approved investigation method.':'لم تتوفر المعلومات المطلوبة. أعد المحاولة لاحقاً أو استخدم طريقة تحقيق أخرى معتمدة.','Administrators can acknowledge threats, link evidence to a case and record a resolution. Exceptions affect notifications while retaining the original risk result. Scoring changes need an independent administrator’s approval.':'يمكن للمسؤولين مراجعة التهديدات وربط الأدلة بحادثة وتسجيل الحل. تؤثر الاستثناءات في الإشعارات مع الاحتفاظ بنتيجة الخطورة الأصلية. تحتاج تغييرات التقييم إلى موافقة مسؤول مستقل.','Monthly AI summaries are drafts that need review. Machine learning highlights unusual activity; it does not prove that malware is present.':'الملخصات الشهرية بالذكاء الاصطناعي مسودات تحتاج إلى مراجعة. يحدد التعلم الآلي النشاط غير المعتاد ولا يثبت وجود برمجيات ضارة.',
 'Skip to content':'الانتقال إلى المحتوى','Loading recorded evidence…':'جارٍ تحميل الأدلة المسجلة…','Working…':'جارٍ التنفيذ…','Chrome extension':'إضافة Chrome','Report periods':'فترات التقارير','UTC · Recorded scans':'UTC · الفحوصات المسجلة','Monitor · ExtSecure':'المراقبة · ExtSecure','Inventory · ExtSecure':'المخزون · ExtSecure','Investigate · ExtSecure':'التحقيق · ExtSecure','Govern · ExtSecure':'الإدارة · ExtSecure','Support · ExtSecure':'الدعم · ExtSecure',
 'Your browser · Your decision':'متصفحك · قرارك','A clearer security check.':'فحص أمني أكثر وضوحاً.','Current page':'الصفحة الحالية','Choose a web page':'اختر صفحة ويب','Check this destination before sharing information or downloading a file.':'افحص الموقع قبل مشاركة معلومات أو تنزيل ملف.','Site origin only · Approval blocking active':'عنوان الموقع فقط · حظر المواقع فعال','File check':'فحص ملف','Manager workspace':'لوحة المدير','Evidence at a glance.':'الأدلة في نظرة واحدة.','Review findings, manage incident cases and inspect monthly reports.':'راجع النتائج وأدر الحوادث الأمنية واطلع على التقارير الشهرية.','Open security console':'فتح لوحة الأمان','Approved access · Backend scoring':'وصول معتمد · تقييم الخطورة على الخادم','Review alerts':'مراجعة التنبيهات','Lifetime recorded checks':'جميع الفحوصات المسجلة','Confirmed high-severity results':'نتائج مؤكدة عالية الخطورة','Open and acknowledged alerts':'تنبيهات مفتوحة أو تمت مراجعتها','Keep confirmed threats and incomplete checks in view. A low score reflects available evidence; it does not guarantee safety.':'تابع التهديدات المؤكدة والفحوصات غير المكتملة. تعكس الدرجة المنخفضة الأدلة المتاحة ولا تضمن الأمان.','There are no scans yet. Start with a page or downloaded file; its evidence will appear here.':'لا توجد فحوصات بعد. ابدأ بصفحة أو ملف محمّل لتظهر أدلته هنا.',
 'Confirmed findings':'النتائج المؤكدة','No confirmed findings':'لا توجد مؤشرات مؤكدة','The lookup was unavailable. This is not a safe result.':'لم تتوفر نتيجة الاستعلام. لا تعني هذه النتيجة أن الهدف آمن.','This assessment found no confirmed signals in the checks performed.':'لم يجد التقييم مؤشرات مؤكدة في الفحوصات التي أُجريت.','Risk is scored by the backend.':'يقيّم الخادم مستوى الخطورة.','An administrator exception applies. Original risk evidence remains recorded.':'يوجد استثناء معتمد من المسؤول. تبقى أدلة الخطورة الأصلية مسجلة.','File reputation check':'فحص سمعة الملف','Choose a downloaded file':'اختر ملفاً محمّلاً','Downloaded file':'الملف المحمّل','File contents stay here. Only SHA-256 goes to the backend.':'يبقى محتوى الملف على جهازك. تُرسل بصمة SHA-256 فقط إلى الخادم.','Maximum 32 MiB · Nothing is uploaded automatically':'الحد الأقصى 32 MiB · لا يتم رفع أي ملف تلقائياً','Or paste an existing file hash':'أو ألصق بصمة ملف موجودة','64 hexadecimal characters':'64 رمزاً بنظام العد الست عشري','The backend checks hash reputation with VirusTotal and records an explainable risk result.':'يتحقق الخادم من سمعة البصمة عبر VirusTotal ويسجل نتيجة خطورة مع أسبابها.','Before you open the file':'قبل فتح الملف','An unknown hash or unavailable lookup means Unknown. Never treat it as a clean file.':'تعني البصمة غير المعروفة أو الاستعلام غير المتاح أن النتيجة غير معروفة. لا تعتبر الملف سليماً.','Use a file you are authorized to check. Large files can be hashed separately and checked using their SHA-256 digest.':'استخدم ملفاً لديك صلاحية فحصه. يمكن حساب بصمة الملفات الكبيرة بأداة منفصلة ثم فحص SHA-256.','Review my history':'مراجعة سجلي','Web address':'عنوان الموقع','Check a web destination':'فحص موقع ويب','A private first step':'خطوة أولى تراعي الخصوصية','Include the page path in the lookup. Query strings and fragments are always removed.':'تضمين مسار الصفحة في الاستعلام. تُزال دائماً معاملات الاستعلام وأجزاء الرابط.','By default, only the site origin is checked. The cleaned address is sent through your backend to VirusTotal after you choose Check destination.':'يُفحص عنوان الموقع الأساسي افتراضياً. يُرسل الرابط المنقح عبر الخادم إلى VirusTotal بعد اختيار فحص الموقع.',
 'Risk':'الخطورة','Checked':'تاريخ الفحص','Inspect':'عرض الأدلة','Filter recorded results':'تصفية النتائج المسجلة','Filter results…':'تصفية النتائج…','Threat':'التهديد','Detected':'تاريخ الكشف','Review an alert':'مراجعة تنبيه','Alert':'التنبيه','New status':'الحالة الجديدة','Record alert decision':'تسجيل قرار التنبيه','Your role has view-only access.':'دورك يسمح بالعرض فقط.','Delivery outcomes are recorded under Security events. Changing status does not resend notifications.':'تُسجل نتائج تسليم الإشعارات ضمن الأحداث الأمنية. لا يؤدي تغيير الحالة إلى إعادة إرسال الإشعار.','Severity levels':'مستويات الخطورة','Minimum':'الحد الأدنى','Maximum':'الحد الأقصى','How the score works':'كيف يُحسب التقييم','Points per confirmed signal':'نقاط كل مؤشر مؤكد','Signal':'المؤشر','Points':'النقاط','Explanation':'الشرح','Unknown means that no check could be assessed. It is separate from Low risk.':'تعني النتيجة غير المعروفة تعذر تقييم الفحوصات. وهي مختلفة عن الخطورة المنخفضة.','Only confirmed signals contribute points. The backend caps the score at 100 and preserves missing checks in assessment completeness.':'تضيف المؤشرات المؤكدة فقط نقاطاً. يحدد الخادم الدرجة القصوى عند 100 ويبين الفحوصات المفقودة في اكتمال التقييم.','Review security policies':'مراجعة السياسات الأمنية',
 'Exceptions change notification handling. They do not lower a score or erase the original finding.':'تغير الاستثناءات طريقة معالجة الإشعارات. ولا تخفض الدرجة أو تمحو النتيجة الأصلية.','Add a controlled exception':'إضافة استثناء معتمد','Match type':'نوع المطابقة','Exact URL or domain':'الرابط أو النطاق المحدد','Expiry (UTC)':'انتهاء الصلاحية (UTC)','Save exception':'حفظ الاستثناء','Deactivate an exception':'تعطيل استثناء','Exception':'الاستثناء','Deactivate exception':'تعطيل الاستثناء','Deactivate this exception. Original risk evidence stays recorded.':'تعطيل هذا الاستثناء مع الاحتفاظ بأدلة الخطورة الأصلية.','Exception audit trail':'سجل تدقيق الاستثناءات','State':'الحالة','Monthly evidence':'الأدلة الشهرية','Choose a completed calendar month in UTC.':'اختر شهراً تقويمياً مكتملاً بحسب UTC.','Report month':'شهر التقرير','Monthly total':'الإجمالي الشهري','Recorded high-severity results':'نتائج عالية الخطورة مسجلة','Unassessable checks':'فحوصات تعذر تقييمها','Monthly alert records':'التنبيهات الشهرية المسجلة','Machine-learning review':'مراجعة التعلم الآلي','Run monthly ML analysis':'تحليل الشهر بالتعلم الآلي','Run an activity review':'إجراء تحليل النشاط','At least 30 active historical days and three distinct observations are needed.':'يلزم توفر 30 يوماً سابقاً نشطاً وثلاث ملاحظات مختلفة على الأقل.','Learns from 90 days before the selected month. Unusual activity supports investigation; it does not establish a threat or change scan risk.':'يتعلم النموذج من الأيام التسعين السابقة للشهر المحدد. يساعد النشاط غير المعتاد في التحقيق ولا يثبت وجود تهديد أو يغير خطورة الفحص.','AI-written monthly summary':'الملخص الشهري بالذكاء الاصطناعي','The backend combines aggregate statistics with the ML evidence. Review the saved draft before delivering it to administrators.':'يجمع الخادم الإحصاءات وأدلة التعلم الآلي. راجع المسودة المحفوظة قبل إرسالها للمسؤولين.','Managers can review saved reports and ML results. Administrators prepare and deliver reports.':'يمكن للمديرين مراجعة التقارير المحفوظة ونتائج التعلم الآلي. يتولى المسؤولون إعداد التقارير وإرسالها.','Generate LLM draft':'إنشاء مسودة بالنموذج اللغوي','Send reviewed report':'إرسال التقرير بعد المراجعة','Saved report body · Read only':'نص التقرير المحفوظ · للقراءة فقط','Saved report history':'سجل التقارير المحفوظة','Month':'الشهر','Generated':'تاريخ الإنشاء','Sent':'تاريخ الإرسال','Channel':'القناة',
 'Pending registrations':'طلبات التسجيل المعلقة','Registration':'طلب التسجيل','Assign role':'تحديد الدور','Record access decision':'تسجيل قرار الوصول','Approved accounts':'الحسابات المعتمدة','Source':'المصدر','Change account access':'تغيير صلاحيات الحساب','Account':'الحساب','Apply access change':'تطبيق تغيير الصلاحيات','Privilege guide':'دليل الصلاحيات','Access':'الوصول','Only the Head of Administrator approves access or changes account privileges. Every role completes password and authenticator sign-in.':'يعتمد رئيس المسؤولين وحده الحسابات ويغير صلاحياتها. تتطلب جميع الأدوار كلمة مرور ورمز تطبيق المصادقة.','Check files and destinations; own history and guidance.':'فحص الملفات والمواقع وطلب الوصول، مع عرض السجل الشخصي والإرشادات.','Review monitoring and reports; manage alerts and cases.':'مراجعة المراقبة والتقارير وإدارة التنبيهات والحوادث وطلبات المواقع.','Security operations, policies, exceptions, privacy and report delivery.':'إدارة العمليات والسياسات والاستثناءات والخصوصية وطلبات المواقع وتسليم التقارير.','All workflows plus registration approval and account access control.':'جميع المهام، إضافة إلى اعتماد التسجيلات وإدارة صلاحيات الحسابات.',
 'Case':'الحادثة','Assigned to':'المسؤول','Source scan':'الفحص المرتبط','Case title':'عنوان الحادثة','Assign to':'تعيين المسؤول','Open an investigation':'فتح تحقيق','Open incident case':'فتح حادثة أمنية','Investigation workspace':'لوحة التحقيق','Inspect source evidence':'عرض الأدلة الأصلية','No notes yet':'لا توجد ملاحظات بعد','Record evidence references without private URLs, passwords or personal details.':'سجل مراجع الأدلة دون روابط خاصة أو كلمات مرور أو تفاصيل شخصية.','Add an investigation note':'إضافة ملاحظة تحقيق','Note':'الملاحظة','Update case or record resolution':'تحديث الحادثة أو تسجيل الحل','Assigned investigator':'المحقق المسؤول','Update investigation':'تحديث التحقيق','Linked scan evidence is held during investigation. Resolving a case preserves its score and history.':'يُحتفظ بأدلة الفحص المرتبطة طوال التحقيق. يبقى التقييم والسجل محفوظين بعد حل الحادثة.',
 'Active scoring policy':'سياسة التقييم الحالية','Draft a scoring change':'اقتراح تغيير التقييم','Save policy draft':'حفظ مسودة السياسة','Policy revisions':'مراجعات السياسات','Author':'الكاتب','Reviewer':'المراجع','Revision':'المراجعة','Starts at':'يبدأ عند','Ends at':'ينتهي عند','Proposed points':'النقاط المقترحة','Proposed minimum':'الحد الأدنى المقترح','Submit independent review':'إرسال مراجعة مستقلة','Activate approved policy':'تفعيل السياسة المعتمدة','Drafts do not affect live scores. A different approved administrator must review a draft before activation.':'لا تؤثر المسودات في التقييمات الحالية. يجب أن يراجع مسؤول معتمد آخر المسودة قبل تفعيلها.','You created this draft. Another administrator must review it.':'أنت أنشأت هذه المسودة. يجب أن يراجعها مسؤول آخر.','Data collection and access':'جمع البيانات والوصول إليها','Data':'البيانات','Stored':'البيانات المحفوظة','Purpose':'الغرض','Scan retention period (days)':'مدة الاحتفاظ بالفحوصات بالأيام','Save privacy rules':'حفظ قواعد الخصوصية','Retention preview':'معاينة الاحتفاظ بالبيانات','Eligible scans':'الفحوصات المؤهلة للحذف','Held for cases':'محفوظة للحوادث','Configured period':'المدة المحددة','Investigation evidence is preserved':'تُحفظ أدلة التحقيق','No scan records are currently eligible for deletion.':'لا توجد سجلات فحص مؤهلة للحذف حالياً.',
 'Run a labelled scoring evaluation':'تقييم سيناريوهات مصنفة','Dataset version':'إصدار مجموعة البيانات','Labelled scenarios (JSON)':'السيناريوهات المصنفة (JSON)','Compare policy with baseline':'مقارنة السياسة بخط الأساس','Dataset':'مجموعة البيانات','Policy':'السياسة','Run time':'وقت التشغيل','Evaluation results':'نتائج التقييم','Run':'التشغيل','Active policy':'السياسة الحالية','Baseline policy':'سياسة خط الأساس','True positives':'كشف صحيح للتهديدات','False positives':'إنذارات خاطئة','Missed threats':'تهديدات لم تُكتشف','Scenario':'السيناريو','Expected':'المتوقع','Result':'النتيجة','Prediction':'التنبؤ','Download evaluation evidence':'تنزيل أدلة التقييم','Record a usability or accessibility check':'تسجيل اختبار استخدام أو إمكانية وصول','Task tested':'المهمة المختبرة','Category':'الفئة','Keyboard navigation':'التنقل بلوحة المفاتيح','Colour contrast':'تباين الألوان','Screen reader':'قارئ الشاشة','Understanding risk':'فهم الخطورة','Task workflow':'تنفيذ المهمة','Observed outcome':'النتيجة الملحوظة','Observation':'الملاحظة','Record test':'تسجيل الاختبار','Task':'المهمة','Outcome':'النتيجة','Record a fix or verified retest':'تسجيل إصلاح أو إعادة اختبار مؤكدة','Test record':'سجل الاختبار','Issue status':'حالة المشكلة','Fix or retest evidence':'أدلة الإصلاح أو إعادة الاختبار','Update record':'تحديث السجل','Record actual walkthroughs and observations. A code check alone does not establish accessibility conformance.':'سجل اختبارات الاستخدام الفعلية والملاحظات. لا يثبت فحص الشفرة وحده الالتزام بمعايير إمكانية الوصول.',
 'A useful first workflow':'خطوات أولى مفيدة','Understand the result':'فهم النتيجة','Keep decisions accountable':'توثيق القرارات','Review my account':'مراجعة حسابي','Check a file':'فحص ملف','Your approved access':'صلاحياتك المعتمدة','Detail':'التفصيل','Value':'القيمة','Sign out on this browser':'تسجيل الخروج من هذا المتصفح','Password and authenticator verification completed for this session.':'اكتمل التحقق بكلمة المرور وتطبيق المصادقة لهذه الجلسة.','Your role is assigned by the Head of Administrator. Contact that account owner when your responsibilities change.':'يحدد رئيس المسؤولين دورك. تواصل معه عند تغير مسؤولياتك.','Sessions are stored in Chrome’s memory-only extension storage. Passwords and authenticator secrets are not saved by the extension.':'تُحفظ الجلسات في ذاكرة الإضافة داخل Chrome فقط. لا تحفظ الإضافة كلمات المرور أو أسرار المصادقة.','Record the evidence and why this action is appropriate.':'سجل الأدلة وسبب ملاءمة هذا الإجراء.',
});
Object.assign(AR,{
 'AI risk explanation':'شرح المخاطر بالذكاء الاصطناعي',
 'The model explains recorded evidence and suggests actions. It does not decide risk or prove a file is safe.':'يفسّر النموذج الأدلة المسجلة ويقترح إجراءات. لا يحدد مستوى الخطورة ولا يثبت أمان الملف.',
 'Optionally share bounded page or text-file content with the backend and configured AI provider.':'مشاركة محتوى محدود من الصفحة أو الملف النصي اختياريًا مع الخادم ومزود الذكاء الاصطناعي المهيأ.',
 'Exact scanned public HTTPS URL (optional)':'رابط HTTPS العام المطابق للفحص (اختياري)',
 'Matching UTF-8 text file (optional, maximum 256 KiB)':'ملف UTF-8 نصي مطابق للبصمة (اختياري، بحد أقصى 256 كيلوبايت)',
 'Without optional content, only stored reputation evidence is explained. Binary files use hash evidence. No content is executed. Query strings and fragments are excluded.':'دون المحتوى الاختياري، يُشرح دليل السمعة المسجل فقط. تعتمد الملفات الثنائية على دليل البصمة. لا يُشغّل أي محتوى، وتُستبعد معلمات الرابط وأجزاؤه.',
 'Explain evidence and recommendations':'شرح الأدلة والتوصيات',
 'AI-assisted draft · Review against the original evidence. Original severity is unchanged.':'مسودة بمساعدة الذكاء الاصطناعي · راجعها مع الأدلة الأصلية. مستوى الخطورة الأصلي لم يتغير.',
 'Recommended actions':'الإجراءات الموصى بها',
 'Weekly and monthly AI reports':'تقارير الذكاء الاصطناعي الأسبوعية والشهرية',
 'Completed UTC periods only. Weekly periods begin on Monday. Each saved snapshot includes every alert and AI explanation recorded during that period, plus an aggregate narrative. The downloadable archive contains all rows; identifiers and raw content are excluded from the model prompt.':'فترات مكتملة بتوقيت UTC فقط، وتبدأ الأسابيع يوم الاثنين. يشمل كل تقرير محفوظ جميع التنبيهات والشروح المسجلة خلال الفترة، إضافة إلى ملخص إجمالي. يتضمن الأرشيف القابل للتنزيل جميع السجلات؛ وتُستبعد المعرفات والمحتويات الخام من مدخلات النموذج.',
 'Report frequency':'تكرار التقرير','Weekly':'أسبوعي','Monthly':'شهري','Period start':'بداية الفترة',
 'Generate period report':'إنشاء تقرير الفترة','Saved AI report snapshots':'تقارير الذكاء الاصطناعي المحفوظة',
 'Download complete report archive':'تنزيل أرشيف التقرير كاملًا','No saved AI period reports.':'لا توجد تقارير فترات محفوظة.',
 'Administrators generate reports. Managers can review saved reports.':'ينشئ المسؤولون التقارير. يمكن للمديرين مراجعة التقارير المحفوظة.',
 'AI-assisted draft · Review before sharing with administrators.':'مسودة بمساعدة الذكاء الاصطناعي · راجعها قبل مشاركتها مع المسؤولين.',
});
export function localize(root=document.body){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  while(walker.nextNode()){
    const node=walker.currentNode;
    if(node.parentElement?.closest('script,style,pre,code,textarea,.code,[data-no-translate]'))continue;
    const previous=originals.get(node);
    const original=previous&&node.nodeValue===previous.rendered?previous.source:node.nodeValue,trimmed=original.trim().replace(/^·\s*/, '');
    if(!AR[trimmed])continue;
    const replacement=original.replace(trimmed,translate(trimmed));
    originals.set(node,{source:original,rendered:replacement});
    if(node.nodeValue!==replacement)node.nodeValue=replacement;
  }
  root.querySelectorAll('[aria-label],[placeholder]').forEach(element=>{
    if(element.closest('script,style,pre,code,.code,[data-no-translate]'))return;
    const attributes=originalAttributes.get(element)??{};
    for(const name of ['aria-label','placeholder']){
      const value=element.getAttribute(name),previous=attributes[name];
      const source=previous&&value===previous.rendered?previous.source:value;
      if(!AR[source]){delete attributes[name];continue;}
      const rendered=translate(source);
      attributes[name]={source,rendered};
      if(value!==rendered)element.setAttribute(name,rendered);
    }
    originalAttributes.set(element,attributes);
  });
}
export function observeLocalization(root=document.body){localize(root);const observer=new MutationObserver(()=>localize(root));observer.observe(root,{childList:true,subtree:true,characterData:true});return observer;}
