"""Containment precedes whitelist grants and requires an investigated, audited release."""
from sqlalchemy import select
from alba_security.threat_blocks import ThreatBlock, block_identity
from test_governance import system as sqlite_system, INGEST, SECRET
import os, re
import pytest
from argon2 import PasswordHasher
from fastapi.testclient import TestClient
from sqlalchemy.engine import make_url
from alba_security.api import create_app
from alba_security.admin_auth import AdminAuth
from alba_security.models import Base

@pytest.fixture
def system(tmp_path):
    url=os.environ.get('EXTSECURE_CONTAINMENT_PG_URL')
    if not url:
        yield from sqlite_system.__wrapped__(tmp_path)
        return
    # Cleanup is permitted only for the disposable database generated by the QA launcher.
    assert re.fullmatch(r'extsecure_test_containment_[a-f0-9]{32}',make_url(url).database or '')
    auth=AdminAuth('hasan',PasswordHasher(time_cost=1,memory_cost=1024,parallelism=1).hash('primary-test-password'),SECRET)
    app=create_app(database_url=url,ingest_token='governance-ingest',admin_auth=auth,alert_notifier=lambda **_:[])
    try:
        with TestClient(app) as client:
            first=client.post('/api/admin/login',json={'username':'hasan','password':'primary-test-password'}).json()
            second=client.post('/api/admin/verify',json={'challenge_token':first['challenge_token'],'totp_code':auth.totp.now()})
            assert second.status_code==200,second.text
            yield client,app,{'hasan':{'Authorization':'Bearer '+second.json()['access_token']}},tmp_path/'unused.sqlite'
    finally:
        from alba_security.postgresql import VIEW_SQL
        with app.state.engine.begin() as connection:
            for name in VIEW_SQL:
                quoted=app.state.engine.dialect.identifier_preparer.quote(name)
                connection.exec_driver_sql("DROP VIEW IF EXISTS " + quoted)
        Base.metadata.drop_all(app.state.engine)
        app.state.engine.dispose()



def submit(client, code='malicious_url', state='detected', kind='url', target='https://danger.example/private?secret=PRIVATE'):
    response = client.post('/api/scans', headers=INGEST, json={'device_id':'containment-test', 'device_name':'Containment test device',
        'target_kind':kind, 'target':target, 'signals':[{'code':code,'status':state}]})
    assert response.status_code == 201, response.text
    return response.json()


def investigate(client, headers, block):
    case = client.get('/api/cases/'+block['case_id'], headers=headers).json()
    for status in ['investigating','resolved']:
        response=client.post('/api/cases/'+case['id']+'/status', headers=headers,
            json={'status':status,'assignee':case['assignee'],'expected_revision':case['revision'],'reason':'Verified containment evidence and completed investigation'})
        assert response.status_code == 200, response.text
        case=response.json()
    return case


def test_high_result_creates_atomic_block_and_incident(system):
    client, app, headers, _ = system
    result=submit(client)
    assert result['severity']=='Critical'
    block=result['containment']
    assert block['active'] and block['case_id']
    with app.state.session_factory() as db:
        row=db.get(ThreatBlock,block['id'])
        assert row.scan_id==result['id']
        assert 'PRIVATE' not in row.target_display
    case=client.get('/api/cases/'+block['case_id'],headers=headers['hasan']).json()
    assert case['device_name']=='Containment test device'
    assert case['timeline'][0]['action']=='created'
    assert case['containment']['active']


def test_existing_permanent_whitelist_cannot_bypass_high_risk(system):
    client, _, headers, _ = system
    h=headers['hasan']; target='https://danger.example/approved'
    req=client.post('/api/access/requests',headers=h,json={'target':target,'reason':'Expected business destination for test'}).json()
    approved=client.post('/api/access/requests/'+req['id']+'/review',headers=h,json={'confirmed':True,'decision':'whitelist','whitelist_forever':True,'expected_revision':req['revision'],'reason':'Head reviewed own destination and business purpose'})
    assert approved.status_code==200, approved.text
    submit(client)
    check=client.post('/api/access/check',headers=h,json={'target':target})
    assert check.json()['threat_blocked'] and not check.json()['allowed']
    assert client.post('/api/access/consume',headers=h,json={'target':target}).status_code==403
    assert client.post('/api/access/requests',headers=h,json={'target':target,'reason':'Request cannot bypass active threat'}).status_code==403


def test_hostname_block_covers_protocol_port_and_other_paths(system):
    client, _, headers, _ = system
    submit(client)
    for target in ['http://danger.example/other','https://danger.example:8443/other','https://DANGER.example./']:
        assert client.post('/api/access/check',headers=headers['hasan'],json={'target':target}).json()['threat_blocked']
    assert not client.post('/api/access/check',headers=headers['hasan'],json={'target':'https://danger.example.evil/'}).json().get('threat_blocked')


def test_release_requires_confirmation_and_resolved_latest_case(system):
    client, _, headers, _ = system
    block=submit(client)['containment']; path='/api/threat-blocks/'+block['id']+'/release'
    body={'confirmed':False,'expected_revision':block['revision'],'reason':'Reviewed source evidence and release rationale'}
    assert client.post(path,headers=headers['hasan'],json=body).status_code==422
    body['confirmed']=True
    assert client.post(path,headers=headers['hasan'],json=body).status_code==409
    investigate(client,headers['hasan'],block)
    response=client.post(path,headers=headers['hasan'],json=body)
    assert response.status_code==200, response.text
    assert not response.json()['active']


def test_resolving_case_does_not_implicitly_release_block(system):
    client, _, headers, _ = system
    block=submit(client)['containment']
    investigate(client,headers['hasan'],block)
    assert client.post('/api/access/check',headers=headers['hasan'],json={'target':'https://danger.example/'}).json()['threat_blocked']


def test_new_threat_reactivates_released_block_and_rejects_stale_release(system):
    client, _, headers, _ = system
    h=headers['hasan']; first=submit(client)['containment'];investigate(client,h,first)
    body={'confirmed':True,'expected_revision':first['revision'],'reason':'Investigation supports explicit release'}
    path='/api/threat-blocks/'+first['id']+'/release'
    assert client.post(path,headers=h,json=body).status_code==200
    second=submit(client)['containment']
    assert second['active'] and second['id']==first['id'] and second['revision']>first['revision']
    assert second['case_id']!=first['case_id']
    assert client.post(path,headers=h,json=body).status_code==409


def test_low_and_unknown_do_not_create_blocks(system):
    client, _, headers, _ = system
    for code,state in [('malicious_url','clear'),('malicious_url','unknown'),('suspicious_url','detected')]:
        assert submit(client,code,state)['containment'] is None
    assert client.get('/api/threat-blocks',headers=headers['hasan']).json()==[]


def test_low_rescan_keeps_existing_high_risk_block(system):
    client, _, _, _ = system
    block=submit(client)['containment']
    later=submit(client,state='clear')
    assert later['severity']=='Low' and later['containment']['id']==block['id'] and later['containment']['active']


def test_file_hash_is_blocklisted_without_file_bytes(system):
    client, _, headers, _ = system
    result=submit(client,'malicious_file_hash',kind='download',target='a'*64)
    assert result['containment']['kind']=='file' and result['containment']['host'] is None
    assert client.get('/api/threat-blocks',headers=headers['hasan']).json()[0]['fingerprint']=='a'*64


def test_new_routes_reject_anonymous_and_ingest_identities(system):
    client, _, _, _ = system
    assert client.get('/api/threat-blocks').status_code==401
    assert client.get('/api/threat-blocks',headers=INGEST).status_code==401


def test_threat_identity_is_canonical_and_does_not_retain_private_urls():
    assert block_identity('url','https://DANGER.example./private?secret=1')[1]==block_identity('url','http://danger.example/')[1]
    assert block_identity('url','https://danger.example/')[1]!=block_identity('url','https://danger.example.evil/')[1]
