"""Rebuild deterministic PostgreSQL DDL from the application's model metadata."""
from pathlib import Path
import sys
from sqlalchemy.dialects.postgresql import dialect
from sqlalchemy.schema import CreateTable,CreateIndex
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'src'))
from alba_security.database_migration import load_metadata
from alba_security.postgresql import VIEW_SQL


def export_schema():
    metadata=load_metadata();pg=dialect()
    chunks=['-- Generated by scripts/export_database_schema.py. For a new empty database.','BEGIN;']
    for table in metadata.sorted_tables:chunks.append(str(CreateTable(table).compile(dialect=pg)).strip()+';')
    for table in metadata.sorted_tables:
        for index in sorted(table.indexes,key=lambda i:i.name):
            chunks.append(str(CreateIndex(index).compile(dialect=pg)).strip()+';')
    for name,sql in VIEW_SQL.items():chunks.append('CREATE VIEW '+name+' AS '+sql+';')
    chunks.append('COMMIT;')
    return '\n\n'.join('\n'.join(line.rstrip() for line in chunk.splitlines()) for chunk in chunks)+'\n'


if __name__=='__main__':
    target=ROOT/'sql/schema.sql';target.write_text(export_schema(),encoding='utf-8')
    print('Exported PostgreSQL schema; no database connection or credentials used.')
